import { beforeEach, describe, expect, it, vi } from 'vitest';
vi.mock('../auth/authClient.js', () => { class AuthRequestError extends Error { constructor(message, status) { super(message); this.status = status; } } return { AuthRequestError, authRequest: vi.fn() }; });
import { AuthRequestError, authRequest } from '../auth/authClient.js';
import { collectReceivable, getReceivable, getReceivables, ReceivableRequestError, reverseReceivableCollection } from './receivablesClient.js';
beforeEach(() => vi.mocked(authRequest).mockReset().mockResolvedValue([]));
describe('receivables request policy', () => {
  it('uses server-backed property-scoped routes and idempotency keys', async () => { await getReceivables({ status: 'open', age: '31_60' }); await getReceivable('receivable-id'); await collectReceivable('receivable-id', { amount: '12.00', method: 'Tarjeta' }, '00000000-0000-4000-8000-000000000001'); await reverseReceivableCollection('receivable-id', 'entry-id', { reason: 'Correction' }, '00000000-0000-4000-8000-000000000002'); expect(authRequest).toHaveBeenNthCalledWith(1, '/api/receivables?status=open&age=31_60', { signal: undefined }); expect(authRequest).toHaveBeenNthCalledWith(3, '/api/receivables/receivable-id/collections', expect.objectContaining({ headers: { 'Idempotency-Key': '00000000-0000-4000-8000-000000000001' } })); expect(authRequest).toHaveBeenNthCalledWith(4, '/api/receivables/receivable-id/collections/entry-id/reverse', expect.objectContaining({ method: 'POST' })); });
  it('scenario: Frontend and API errors normalize permission, malformed, and ambiguous failures', async () => { vi.mocked(authRequest).mockRejectedValueOnce(new AuthRequestError('private', 403)); await expect(getReceivables()).rejects.toMatchObject({ name: 'ReceivableRequestError', status: 403 }); vi.mocked(authRequest).mockRejectedValueOnce(new AuthRequestError('invalid', 400)); await expect(getReceivable('id')).rejects.toMatchObject({ status: 400 }); vi.mocked(authRequest).mockRejectedValueOnce(new Error('socket')); await expect(getReceivable('id')).rejects.toMatchObject({ reloadRecommended: true }); expect(ReceivableRequestError).toBeTypeOf('function'); });
});
