import { useState, useMemo } from 'react';
import { Dialog } from '../components/ui/Overlay.jsx';
import { Printer, Copy, Check, Building2 } from 'lucide-react';
import { formatMoney } from '../domain/hotelModel.js';

function formatReceiptDateTime(dateStr) { if (!dateStr) return 'Pendiente'; try { return new Date(dateStr).toLocaleString('es-PE', { day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit' }); } catch { return dateStr; } }
export function CashZReportModal({ open, onClose, session, movements = [] }) {
  const [copied, setCopied] = useState(false);
  const calculations = useMemo(() => { if (!session) return null; const sessionMovements = movements.filter((m) => m.sessionId === session.id && m.type !== 'Sesión'); const cashMovements = sessionMovements.filter((m) => !m.method || m.method === 'Efectivo'); const incomeMovements = cashMovements.filter((m) => m.type === 'Ingreso'); const expenseMovements = cashMovements.filter((m) => m.type === 'Egreso'); const incomeTotal = incomeMovements.reduce((sum, m) => sum + (Number(m.amount) || 0), 0); const expenseTotal = expenseMovements.reduce((sum, m) => sum + (Number(m.amount) || 0), 0); const openingAmount = Number(session.openingAmount) || 0; const expectedAmount = session.expectedAmount != null ? Number(session.expectedAmount) : openingAmount + incomeTotal - expenseTotal; const countedAmount = session.countedAmount != null ? Number(session.countedAmount) : null; const difference = session.difference != null ? Number(session.difference) : countedAmount != null ? countedAmount - expectedAmount : 0; let breakdownPart = null; let cleanNotes = session.notes || ''; const match = cleanNotes.match(/\[Conteo Físico PEN:\s*([^\]]+)\]/); if (match) { breakdownPart = match[1]; cleanNotes = cleanNotes.replace(/\[Conteo Físico PEN:[^\]]+\]/, '').replace(/^[\s·]+|[\s·]+$/g, ''); } return { sessionMovements, incomeTotal, expenseTotal, openingAmount, expectedAmount, countedAmount, difference, breakdownPart, cleanNotes }; }, [session, movements]);
  if (!open || !session || !calculations) return null;
  const { sessionMovements, incomeTotal, expenseTotal, openingAmount, expectedAmount, countedAmount, difference, breakdownPart, cleanNotes } = calculations;
  // Thermal print contract: @media print keeps the ticket at width: 80mm; rules live in index.css.
  const result = Math.abs(difference) < 0.01 ? 'exact' : difference > 0.01 ? 'surplus' : 'deficit'; const diffLabel = result === 'exact' ? 'CUADRE EXACTO (S/ 0.00)' : result === 'surplus' ? `SOBRANTE (+${formatMoney(difference)})` : `FALTANTE (${formatMoney(difference)})`;
  const handleCopy = () => { const text = ['========================================', '       HOTEL PARK PLAZA & SUITES        ', '       CORTE Z · CIERRE DE CAJA        ', '========================================', `ID Sesión:   ${session.id}`, `Responsable: ${session.responsible}`, `Turno:       ${session.shift}`, `Apertura:    ${formatReceiptDateTime(session.openedAt)}`, `Cierre:      ${formatReceiptDateTime(session.closedAt || new Date().toISOString())}`, `Estado:      ${session.status.toUpperCase()}`, '----------------------------------------', '          BALANCE GENERAL (PEN)         ', '----------------------------------------', `(+) Fondo Apertura:     ${formatMoney(openingAmount)}`, `(+) Total Ingresos:     ${formatMoney(incomeTotal)}`, `(-) Total Egresos:      ${formatMoney(expenseTotal)}`, '----------------------------------------', `(=) Saldo Esperado:     ${formatMoney(expectedAmount)}`, `(*) Efectivo Contado:   ${countedAmount != null ? formatMoney(countedAmount) : 'No registrado'}`, '----------------------------------------', `DIFERENCIA:             ${diffLabel}`, '----------------------------------------', breakdownPart ? `DESGLOSE FÍSICO:\n${breakdownPart}\n----------------------------------------` : '', cleanNotes ? `OBSERVACIONES:\n${cleanNotes}\n----------------------------------------` : '', '========================================', 'FIRMAS DE CONFORMIDAD:', '', '_______________________   _______________________', 'Firma Cajero Saliente     Firma Supervisor/Admin', 'DNI:                      DNI:', '========================================'].filter(Boolean).join('\n'); navigator.clipboard?.writeText(text).then(() => { setCopied(true); setTimeout(() => setCopied(false), 2500); }).catch(() => {}); };
  const handlePrint = () => window.print();
  const row = (label, value, extra = '') => <div className="cash-z-row"><span className={extra}>{label}</span><strong className={extra}>{value}</strong></div>;
  return <Dialog open={open} onClose={onClose} title="Comprobante de Cierre de Caja · Corte Z" description="Ticket de arqueo y liquidación final de turno en formato térmico estándar (80mm).">
    <div className="cash-z-modal-content"><div id="corte-z-printable-ticket" className="cash-z-ticket">
      <div className="cash-z-header"><div className="cash-z-brand"><Building2 size={18} /><span>PARK PLAZA HOTEL</span></div><div className="cash-z-muted">HOTEL & SUITES DE LUJO *****</div><div className="cash-z-muted">RUC: 20458912301 · CUSCO / LIMA</div><div className="cash-z-muted">TEL: +51 (01) 445-8900</div></div>
      <div className="cash-z-title"><strong>CORTE Z · CIERRE DE CAJA</strong><span>DOCUMENTO INTERNO DE CONTROL Y AUDITORÍA</span></div>
      <div className="cash-z-session">{row('Sesión ID:', `#${session.id.slice(0, 10).toUpperCase()}`)}{row('Cajero / Responsable:', session.responsible)}{row('Turno Asignado:', session.shift)}{row('Apertura:', formatReceiptDateTime(session.openedAt))}{row('Cierre:', formatReceiptDateTime(session.closedAt || new Date().toISOString()))}{row('Estado Final:', session.status.toUpperCase(), session.status === 'Abierta' ? 'is-open' : 'is-closed')}</div>
      <div className="cash-z-divider" /><section className="cash-z-section"><div className="cash-z-section-title">[ RESUMEN FINANCIERO DE EFECTIVO ]</div><div className="cash-z-summary">{row('(+) Fondo Inicial Apertura:', formatMoney(openingAmount))}{row('(+) Total Ingresos Turno:', `+${formatMoney(incomeTotal)}`, 'is-income')}{row('(-) Total Egresos Turno:', `-${formatMoney(expenseTotal)}`, 'is-expense')}<div className="cash-z-rule" />{row('(=) Saldo Teórico Esperado:', formatMoney(expectedAmount), 'is-emphasis')}{row('(•) Efectivo Contado Físico:', countedAmount != null ? formatMoney(countedAmount) : 'Pendiente', 'is-emphasis')}<div className="cash-z-rule cash-z-rule-strong" /><div className={`cash-z-result cash-z-result-${result}`}><span>Resultado de Auditoría / Cuadre</span><strong>{diffLabel}</strong></div></div></section>
      {breakdownPart && <><div className="cash-z-divider" /><section className="cash-z-section"><div className="cash-z-section-title">[ CONTEO FÍSICO DETALLADO (PEN) ]</div><div className="cash-z-breakdown">{breakdownPart}</div></section></>}
      {sessionMovements.length > 0 && <><div className="cash-z-divider" /><section className="cash-z-section"><div className="cash-z-section-title">[ MOVIMIENTOS REGISTRADOS ({sessionMovements.length}) ]</div><div className="cash-z-movements">{sessionMovements.slice(0, 10).map((m) => <div key={m.id} className="cash-z-row"><span className="cash-z-movement-concept">{m.type === 'Ingreso' ? '+ ' : '- '}{m.concept || 'Movimiento'}</span><strong className={m.type === 'Ingreso' ? 'is-income' : 'is-expense'}>{formatMoney(m.amount)}</strong></div>)}{sessionMovements.length > 10 && <div className="cash-z-more">... y {sessionMovements.length - 10} movimiento(s) más.</div>}</div></section></>}
      {cleanNotes && <><div className="cash-z-divider" /><section className="cash-z-notes"><strong>OBSERVACIONES:</strong><span>{cleanNotes}</span></section></>}
      <div className="cash-z-divider cash-z-signature-divider" /><div className="cash-z-signatures"><div><strong>FIRMA CAJERO</strong><span>{session.responsible}</span><small>DNI: ______________</small></div><div><strong>SUPERVISOR / ADMIN</strong><span>Control Operativo</span><small>DNI: ______________</small></div></div><footer className="cash-z-footer"><div>Generado por Park Plaza Hotel PMS/POS v2.4</div><div>Impreso el: {formatReceiptDateTime(new Date().toISOString())}</div><div>*** FIN DEL CORTE Z ***</div></footer>
    </div><div className="cash-z-actions"><div className="cash-z-action-group"><button type="button" className="btn btn-outline btn-sm cash-z-action-button" onClick={handleCopy} title="Copiar texto resumen para WhatsApp o correo">{copied ? <Check size={14} /> : <Copy size={14} />}<span>{copied ? 'Copiado' : 'Copiar'}</span></button><button type="button" className="btn btn-primary btn-sm cash-z-action-button" onClick={handlePrint}><Printer size={14} /><span>Imprimir Corte Z</span></button></div><button type="button" className="btn btn-outline btn-sm" onClick={onClose}>Cerrar</button></div></div>
  </Dialog>;
}
