import { useState, useEffect } from 'react';
import { useHotelCommands } from '../state/hotelContext';
import { useActionPermission } from '../components/auth/useActionPermission';
import { CASH_PAYMENT_METHODS } from './cashModel';
import { formatMoney } from '../domain/hotelModel';
import { ShieldAlert, FileText, AlertTriangle, ArrowDownRight, ArrowUpRight, Tag } from 'lucide-react';

const EXPENSE_CATEGORIES = [
  { id: 'caja_chica', label: 'Caja Chica - Compras de Emergencia', icon: '🛒', desc: 'Insumos de aseo, alimentos menores, ferretería o cafetería urgente.' }, { id: 'proveedores', label: 'Pago a Proveedores Menores', icon: '📦', desc: 'Agua de bidón, diarios, mensajería, flores o lavandería express.' }, { id: 'reembolso', label: 'Devolución / Reembolso a Huésped', icon: '↩️', desc: 'Devolución de depósito en garantía o anulación de cobro en recepción.' }, { id: 'movilidad', label: 'Movilidad y Transporte', icon: '🚕', desc: 'Taxi nocturno de personal, recojo de compras o traslados de emergencia.' }, { id: 'cash_drop', label: 'Pase a Bóveda / Caja Fuerte (Cash Drop)', icon: '🛡️', desc: 'Remesa de retiro por exceso de efectivo en gaveta.' }, { id: 'mantenimiento', label: 'Mantenimiento Urgente', icon: '🔧', desc: 'Reparaciones menores inmediatas de cerrajería, plomería o electricidad.' }, { id: 'otros_egreso', label: 'Otros Egresos Justificados', icon: '📝', desc: 'Cualquier otro egreso autorizado por supervisor de turno.' },
];
const INCOME_CATEGORIES = [
  { id: 'cobro_extra', label: 'Cobro Extraordinario en Efectivo', icon: '💵', desc: 'Servicios de lavandería, late check-out o tours cobrados en recepción.' }, { id: 'reposicion', label: 'Aporte / Reposición de Fondo Fijo', icon: '💰', desc: 'Inyección de sencillo o reposición de fondo por supervisor.' }, { id: 'cambio_divisa', label: 'Cambio de Divisas / Sencillo', icon: '💱', desc: 'Intercambio de denominaciones para gaveta de recepción.' }, { id: 'otros_ingreso', label: 'Otros Ingresos Justificados', icon: '✨', desc: 'Cualquier otro ingreso operativo autorizado.' },
];
const VOUCHER_TYPES = ['Boleta de Venta', 'Factura', 'Recibo de Caja Chica', 'Vale de Egreso / Remesa', 'Sin Comprobante'];

export function CashMovementEnhancedForm({ initialPreset, onClose, notify }) {
  const { cashCommands } = useHotelCommands(); const allowed = useActionPermission('CASH_MOVEMENT');
  const [type, setType] = useState(initialPreset?.type || 'Egreso');
  const [category, setCategory] = useState(initialPreset?.category || (initialPreset?.type === 'Ingreso' ? INCOME_CATEGORIES[0].label : EXPENSE_CATEGORIES[0].label));
  const [concept, setConcept] = useState(initialPreset?.concept || ''); const [amount, setAmount] = useState(initialPreset?.amount || '');
  const [beneficiary, setBeneficiary] = useState(initialPreset?.beneficiary || ''); const [voucherType, setVoucherType] = useState(initialPreset?.voucherType || 'Recibo de Caja Chica'); const [voucherNumber, setVoucherNumber] = useState(initialPreset?.voucherNumber || ''); const [method] = useState('Efectivo'); const [busy, setBusy] = useState(false);
  useEffect(() => { if (initialPreset) { if (initialPreset.type) setType(initialPreset.type); if (initialPreset.category) setCategory(initialPreset.category); if (initialPreset.concept) setConcept(initialPreset.concept); if (initialPreset.amount != null) setAmount(initialPreset.amount); if (initialPreset.voucherType) setVoucherType(initialPreset.voucherType); if (initialPreset.voucherNumber) setVoucherNumber(initialPreset.voucherNumber); } }, [initialPreset]);
  const handleTypeChange = (newType) => { setType(newType); if (newType === 'Ingreso') { setCategory(INCOME_CATEGORIES[0].label); if (voucherType === 'Recibo de Caja Chica' || voucherType === 'Vale de Egreso / Remesa') setVoucherType('Boleta de Venta'); } else { setCategory(EXPENSE_CATEGORIES[0].label); if (voucherType === 'Boleta de Venta') setVoucherType('Recibo de Caja Chica'); } };
  const applyPreset = (pType, pCat, pConcept, pVoucher) => { setType(pType); setCategory(pCat); setConcept(pConcept); if (pVoucher) setVoucherType(pVoucher); };
  const numericAmount = Number(amount) || 0; const isCashDrop = category.includes('Cash Drop') || category.includes('Bóveda'); const isHighExpense = type === 'Egreso' && numericAmount > 150;
  const submit = async (event) => { event.preventDefault(); if (!cashCommands) return; if (numericAmount <= 0) { notify?.('Monto inválido', 'El importe debe ser mayor a S/ 0.00.', 'error'); return; } if (isHighExpense && !beneficiary.trim() && !concept.trim()) { notify?.('Justificación requerida', 'Todo egreso mayor a S/ 150.00 requiere indicar el beneficiario y el concepto detallado.', 'error'); return; } setBusy(true); try { const categoryTag = `[${category.split(' - ')[0] || category}]`; const parts = [categoryTag, concept.trim()]; if (beneficiary.trim()) parts.push(`(Benef: ${beneficiary.trim()})`); if (voucherType && voucherType !== 'Sin Comprobante') parts.push(`[${voucherType}${voucherNumber.trim() ? `: ${voucherNumber.trim()}` : ''}]`); let finalConcept = parts.filter(Boolean).join(' '); if (finalConcept.length > 200) finalConcept = finalConcept.slice(0, 197) + '...'; let finalReferenceId = voucherNumber.trim() || undefined; if (isCashDrop && !finalReferenceId) finalReferenceId = `DROP-${Date.now().toString().slice(-8)}`; await cashCommands.move({ type, concept: finalConcept, amount: numericAmount, method: 'Efectivo', referenceId: finalReferenceId }); notify?.(isCashDrop ? 'Remesa registrada' : 'Movimiento registrado', `${type === 'Ingreso' ? 'Ingreso' : 'Egreso'} de ${formatMoney(numericAmount)} registrado con éxito.`, 'success'); onClose(); } catch (error) { notify?.('Error al registrar movimiento', error.message || 'Ocurrió un error inesperado.', 'error'); } finally { setBusy(false); } };
  if (!allowed) return null; const currentCategories = type === 'Ingreso' ? INCOME_CATEGORIES : EXPENSE_CATEGORIES;
  const control = (extra = '') => `cash-movement-control ${extra}`;
  return <form className={`form-grid cash-movement-form cash-movement-form-${type === 'Ingreso' ? 'income' : 'expense'} ${busy ? 'is-loading' : ''}`} onSubmit={submit}>
    <div className="cash-movement-presets"><span className="cash-movement-eyebrow">Atajos Rápidos de Mostrador</span><div className="cash-movement-preset-list">
      <button type="button" className="btn btn-xs btn-outline cash-movement-preset" onClick={() => applyPreset('Egreso', 'Pase a Bóveda / Caja Fuerte (Cash Drop)', 'Remesa a caja fuerte principal por exceso de efectivo', 'Vale de Egreso / Remesa')}><span>🛡️</span> Pase a Bóveda (Cash Drop)</button>
      <button type="button" className="btn btn-xs btn-outline cash-movement-preset" onClick={() => applyPreset('Egreso', 'Caja Chica - Compras de Emergencia', 'Compra de insumos urgentes para recepción/huésped', 'Recibo de Caja Chica')}><span>🛒</span> Compra Caja Chica</button>
      <button type="button" className="btn btn-xs btn-outline cash-movement-preset" onClick={() => applyPreset('Egreso', 'Movilidad y Transporte', 'Taxi nocturno de personal o envío urgente', 'Recibo de Caja Chica')}><span>🚕</span> Movilidad / Taxi</button>
      <button type="button" className="btn btn-xs btn-outline cash-movement-preset" onClick={() => applyPreset('Egreso', 'Devolución / Reembolso a Huésped', 'Devolución de garantía en efectivo a huésped', 'Vale de Egreso / Remesa')}><span>↩️</span> Reembolso a Huésped</button>
    </div></div>
    <div className="cash-movement-type-selector"><button type="button" className={`cash-movement-type-button cash-movement-type-expense ${type === 'Egreso' ? 'is-selected' : ''}`} onClick={() => handleTypeChange('Egreso')}><ArrowDownRight size={18} /><span>Egreso (Salida de Dinero)</span></button><button type="button" className={`cash-movement-type-button cash-movement-type-income ${type === 'Ingreso' ? 'is-selected' : ''}`} onClick={() => handleTypeChange('Ingreso')}><ArrowUpRight size={18} /><span>Ingreso (Entrada de Dinero)</span></button></div>
    <label className="span-2"><span className="cash-movement-label cash-movement-label-with-icon"><Tag size={15} /> Categoría del Movimiento</span><select className={control()} value={category} onChange={(event) => setCategory(event.target.value)}>{currentCategories.map((c) => <option key={c.id} value={c.label}>{c.icon} {c.label}</option>)}</select></label>
    <div className="cash-movement-amount-grid"><label><span className="cash-movement-label">Importe (PEN S/) *</span><input className={control('cash-movement-amount')} type="number" min="0.01" step="0.01" required placeholder="0.00" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><label><span className="cash-movement-label">Método de Pago</span><select className={control('cash-movement-control-disabled')} disabled value={method}>{CASH_PAYMENT_METHODS.map((item) => <option key={item} value={item}>{item}</option>)}</select></label></div>
    <div className="cash-movement-voucher-box"><div className="cash-movement-voucher-title"><FileText size={16} /> <span>Comprobante de Respaldo Contable</span></div><div className="cash-movement-voucher-grid"><label><span className="cash-movement-field-hint">Tipo Comprobante</span><select className={control('cash-movement-control-compact')} value={voucherType} onChange={(event) => setVoucherType(event.target.value)}>{VOUCHER_TYPES.map((v) => <option key={v} value={v}>{v}</option>)}</select></label><label><span className="cash-movement-field-hint">N° Comprobante / Referencia</span><input className={control('cash-movement-control-compact')} type="text" placeholder="Ej: B001-00421 o REC-015" value={voucherNumber} onChange={(event) => setVoucherNumber(event.target.value)} /></label></div><label><span className="cash-movement-field-hint">Beneficiario / Entregado a (Persona o Empresa) {isHighExpense ? '(Requerido por monto > S/ 150)' : '(Opcional)'}</span><input className={control('cash-movement-control-compact')} type="text" placeholder="Ej: Distribuidora San Lucas SAC / Luis Alva (Conductor)" value={beneficiary} required={isHighExpense} onChange={(event) => setBeneficiary(event.target.value)} /></label></div>
    {isHighExpense && <div className="cash-movement-alert cash-movement-alert-high-expense"><AlertTriangle size={16} /><span>Egreso superior a S/ 150.00: Requiere justificación clara y comprobante de respaldo para auditoría.</span></div>}{isCashDrop && <div className="cash-movement-alert cash-movement-alert-cash-drop"><ShieldAlert size={16} /><span>Pase a Bóveda: El efectivo retirado se ingresará a la caja fuerte principal del hotel. Anote el N° de sobre/remesa.</span></div>}
    <label className="span-2"><span className="cash-movement-label">Concepto / Justificación del Movimiento *</span><textarea className={control()} required rows={2} value={concept} placeholder="Ej: Pago de 5 bidones de agua de mesa para recepción y restaurante..." onChange={(event) => setConcept(event.target.value)} /></label>
    <div className="form-actions span-2 cash-movement-actions"><button type="button" className="btn btn-outline" onClick={onClose} disabled={busy}>Cancelar</button><button type="submit" className="btn btn-primary cash-movement-submit" disabled={busy}>{busy ? 'Guardando...' : type === 'Egreso' ? 'Registrar Egreso' : 'Registrar Ingreso'}</button></div>
  </form>;
}
