import { useDeferredValue, useState } from 'react';
import {
  BedDouble, BellRing, CalendarDays, CheckCircle2, ClipboardCheck, Clock3,
  CreditCard, DoorOpen, Search,
} from 'lucide-react';
import {
  formatMoney, getOrderRequirements, getOrderShortages, ORDER_STATUSES, PAYMENT_METHODS,
  RESERVATION_STATUSES, ROOM_CATEGORIES, ROOM_STATUSES, selectAccountBalance, selectClientName,
} from '../../domain/hotelModel';
import { useHotel } from '../../state/hotelContext';
import { BiometricPanel } from '../biometrics/BiometricPanel';
import { Dialog, Drawer, PrototypeNotice, Tabs, TabPanel } from '../ui/Overlay';
import { executeWithFeedback } from '../ui/actionFeedback';
import {
  DataTable, DetailGrid, EmptyState, Kpi, MetricStrip, PageHeader, SectionHeader, StatusBadge,
} from './SharedViewParts';

const padCalendarPart = (value) => String(value).padStart(2, '0');
const formatCalendarDate = (value) => {
  if (!(value instanceof Date) || Number.isNaN(value.getTime())) return '';
  return `${value.getFullYear()}-${padCalendarPart(value.getMonth() + 1)}-${padCalendarPart(value.getDate())}`;
};
const parseCalendarDate = (value) => {
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(value || '');
  if (!match) return null;
  const [, year, month, day] = match.map(Number);
  const date = new Date(year, month - 1, day);
  return date.getFullYear() === year && date.getMonth() === month - 1 && date.getDate() === day ? date : null;
};
const displayCalendarDate = (value, options) => parseCalendarDate(value)?.toLocaleDateString('es-PE', options) || value || 'No registrado';
const future = (days) => {
  const value = new Date();
  value.setDate(value.getDate() + days);
  return formatCalendarDate(value);
};

const today = () => formatCalendarDate(new Date());
const statusClass = (value) => String(value).toLowerCase().replaceAll(' ', '-');
const formatDateTime = (value) => value ? new Date(value).toLocaleString('es-PE') : 'No registrado';
const getStay = (state, stayId) => state.stays.find((stay) => stay.id === stayId);
const getReservation = (state, reservationId) => state.reservations.find((reservation) => reservation.id === reservationId);
const inventoryAvailable = (item) => item.stock - item.reserved;

export function DashboardView({ navigate }) {
  const { state } = useHotel();
  const available = state.rooms.filter((room) => room.status === 'Disponible').length;
  const occupied = state.rooms.filter((room) => room.status === 'Ocupada').length;
  const occupancy = state.rooms.length ? Math.round((occupied / state.rooms.length) * 100) : 0;
  const openIncidents = state.incidents.filter((item) => item.status !== 'Cerrada');
  const lowStock = state.inventory.filter((item) => inventoryAvailable(item) <= item.minimum);
  const income = state.cashMovements.filter((item) => item.type === 'Ingreso').reduce((sum, item) => sum + item.amount, 0);
  const openBalance = state.accounts.filter((item) => item.status === 'Abierta').reduce((sum, item) => sum + selectAccountBalance(item), 0);
  const activeOrders = state.orders.filter((item) => !['Entregado', 'Pagado', 'Cancelado'].includes(item.status));
  const arrivals = state.reservations.filter((item) => item.status === 'Confirmada').toSorted((a, b) => a.checkIn.localeCompare(b.checkIn));
  const departures = state.stays.filter((item) => item.status === 'Activa').toSorted((a, b) => a.expectedCheckOut.localeCompare(b.expectedCheckOut));
  const poolInside = state.recreationAccess.filter((item) => item.zone === 'Piscina').reduce((sum, item) => sum + item.peopleInside, 0);
  const operation = [
    { label: 'Limpieza', value: state.cleaningTasks.filter((item) => item.status !== 'Aprobada').length, detail: 'sin aprobar', route: 'limpieza' },
    { label: 'Mantenimiento', value: state.maintenanceTickets.filter((item) => item.status !== 'Cerrado').length, detail: 'pendientes de cierre', route: 'mantenimiento' },
    { label: 'Pedidos', value: activeOrders.length, detail: 'por completar', route: 'pedidos-qr' },
    { label: 'Eventos', value: state.events.filter((item) => item.date >= today()).length, detail: 'programados', route: 'eventos' },
    { label: 'Piscina', value: `${poolInside}/${state.poolCapacity}`, detail: 'aforo actual', route: 'recreacion' },
    { label: 'Accesos', value: state.accessLog.filter((item) => item.result === 'Rechazado').length, detail: 'rechazos de sesión', route: 'recreacion' },
    { label: 'Inventario', value: lowStock.length, detail: 'bajo mínimo disponible', route: 'inventario' },
    { label: 'Licores', value: state.inventory.filter((item) => item.category === 'Licores').reduce((sum, item) => sum + inventoryAvailable(item), 0).toFixed(1), detail: 'oz disponibles', route: 'cocina-bar' },
  ];
  return <div className="view-container">
    <PageHeader metadata="Estado actual · datos en memoria" title="Centro de operaciones" description="Lectura transversal de recepción, habitaciones, servicios y control interno." action={<button className="btn btn-primary" onClick={() => navigate('reservas', { type: 'create-reservation' })}>Nueva reserva</button>} />
    <div className="dashboard-kpi-grid">
      <Kpi label="Disponibles" value={available} detail={`${state.rooms.length} habitaciones registradas`} icon={CheckCircle2} />
      <Kpi label="Ocupadas" value={occupied} detail={`${occupancy} % actual`} icon={BedDouble} tone="purple" />
      <Kpi label="Llegadas" value={arrivals.length} detail="Reservas confirmadas" icon={CalendarDays} tone="blue" />
      <Kpi label="Ingresos registrados" value={formatMoney(income)} detail="Movimientos de esta sesión" icon={CreditCard} tone="gold" />
      <Kpi label="Saldos abiertos" value={formatMoney(openBalance)} detail={`${departures.length} estadías activas`} icon={DoorOpen} tone="warning" />
      <Kpi label="Alertas" value={openIncidents.length + lowStock.length} detail="Incidencias + stock disponible bajo" icon={BellRing} tone="red" />
    </div>
    <section aria-labelledby="dashboard-operation-title">
      <SectionHeader id="dashboard-operation-title" eyebrow="Control transversal" title="Pulso operativo" description="Cada indicador abre su módulo y usa solamente registros de la sesión." />
      <div className="operational-strip">{operation.map((item) => <button key={item.label} onClick={() => navigate(item.route)}><span>{item.label}</span><strong>{item.value}</strong><small>{item.detail}</small></button>)}</div>
    </section>
    <div className="dashboard-list-grid">
      <DashboardList title="Llegadas confirmadas" records={arrivals} empty="Sin llegadas confirmadas" onOpen={() => navigate('checkin-checkout')} render={(item) => ({ title: selectClientName(state, item.clientId), detail: `Hab. ${item.roomId} · ${displayCalendarDate(item.checkIn)}`, status: item.status })} />
      <DashboardList title="Salidas previstas" records={departures} empty="Sin estadías activas" onOpen={() => navigate('checkin-checkout')} render={(item) => ({ title: selectClientName(state, item.clientId), detail: `Hab. ${item.roomId} · ${displayCalendarDate(item.expectedCheckOut)}`, status: item.status })} />
      <DashboardList title="Atención prioritaria" records={[...openIncidents, ...lowStock]} empty="Sin alertas abiertas" onOpen={(item) => navigate(item.id.startsWith('INC') ? 'incidencias' : 'inventario')} render={(item) => item.id.startsWith('INC') ? ({ title: item.description, detail: item.roomId ? `Hab. ${item.roomId}` : item.type, status: item.priority }) : ({ title: item.name, detail: `${inventoryAvailable(item)} ${item.unit} disponibles`, status: inventoryAvailable(item) < 0 ? 'Crítico' : 'Bajo mínimo' })} />
    </div>
    <section className="activity-strip" aria-labelledby="activity-title"><div><span className="activity-mark"><Clock3 size={17} /></span><span><strong id="activity-title">Auditoría reciente</strong><small>Actividad local, no histórica</small></span></div><div className="activity-items">{state.auditLog.slice(0, 3).map((entry) => <span key={entry.id}><strong>{entry.action}</strong><small>{entry.module} · {formatDateTime(entry.createdAt)}</small></span>)}</div><button className="text-action" onClick={() => navigate('auditoria')}>Abrir auditoría</button></section>
    <PrototypeNotice>los indicadores describen el estado visible de esta sesión. No afirman resultados diarios, mensuales ni conexión en tiempo real.</PrototypeNotice>
  </div>;
}

function DashboardList({ title, records, empty, onOpen, render }) {
  return <article className="card dashboard-list-card"><div className="card-header"><h3 className="card-title">{title}</h3><span className="list-total">{records.length}</span></div><div className="dashboard-records">{records.slice(0, 4).map((item) => { const detail = render(item); return <button key={item.id} onClick={() => onOpen(item)}><span><strong>{detail.title}</strong><small>{detail.detail}</small></span><StatusBadge>{detail.status}</StatusBadge></button>; })}{records.length === 0 ? <span className="dashboard-list-empty">{empty}</span> : null}</div></article>;
}

export function RoomsView() {
  const { state } = useHotel();
  const [floor, setFloor] = useState('Todos');
  const [status, setStatus] = useState('Todos');
  const [category, setCategory] = useState('Todas');
  const [selectedId, setSelectedId] = useState(null);
  const rooms = state.rooms.filter((room) => (floor === 'Todos' || room.floor === Number(floor)) && (status === 'Todos' || room.status === status) && (category === 'Todas' || room.category === category));
  const floors = [1, 2, 3, 4].map((number) => ({ number, rooms: rooms.filter((room) => room.floor === number) })).filter((item) => item.rooms.length);
  const selected = state.rooms.find((room) => room.id === selectedId);
  const stay = getStay(state, selected?.activeStayId);
  const reservation = getReservation(state, stay?.reservationId);
  const account = state.accounts.find((item) => item.id === stay?.accountId);
  const incidents = state.incidents.filter((item) => item.roomId === selected?.id && item.status !== 'Cerrada');
  return <div className="view-container">
    <PageHeader metadata="38 habitaciones · 4 pisos" title="Mapa de habitaciones" description="Disponibilidad por piso, categoría y estado con contexto de huésped, cuenta y operación." />
    <MetricStrip items={ROOM_STATUSES.map((item) => ({ label: item, value: state.rooms.filter((room) => room.status === item).length }))} label="Habitaciones por estado" />
    <div className="filter-bar"><label>Piso<select value={floor} onChange={(event) => setFloor(event.target.value)}><option>Todos</option><option>1</option><option>2</option><option>3</option><option>4</option></select></label><label>Categoría<select value={category} onChange={(event) => setCategory(event.target.value)}><option>Todas</option>{ROOM_CATEGORIES.map((item) => <option key={item}>{item}</option>)}</select></label><label>Estado<select value={status} onChange={(event) => setStatus(event.target.value)}><option>Todos</option>{ROOM_STATUSES.map((item) => <option key={item}>{item}</option>)}</select></label><span className="filter-result">{rooms.length} habitaciones</span></div>
    <div className="status-legend" aria-label="Leyenda de estados">{ROOM_STATUSES.map((item) => <span key={item} className={`legend-${statusClass(item)}`}><i />{item}</span>)}</div>
    {floors.map((item) => <section key={item.number} aria-labelledby={`floor-${item.number}`}><SectionHeader id={`floor-${item.number}`} eyebrow={`${item.rooms.length} visibles`} title={`Piso ${item.number}`} /><div className="room-floor-grid">{item.rooms.map((room) => <button key={room.id} className={`room-tile status-${statusClass(room.status)}`} onClick={() => setSelectedId(room.id)} aria-label={`Habitación ${room.id}, ${room.category}, ${room.status}`}><span className="room-number">{room.id}</span><span>{room.category} · {room.capacity} persona(s)</span><StatusBadge>{room.status}</StatusBadge><small>{room.guestId ? selectClientName(state, room.guestId) : `${formatMoney(room.nightlyRate)} / noche`}</small><small>Limpieza: {room.cleaningStatus}</small></button>)}</div></section>)}
    {!rooms.length ? <EmptyState title="Sin habitaciones" /> : null}
    <Drawer open={Boolean(selected)} onClose={() => setSelectedId(null)} title={selected ? `Habitación ${selected.id}` : 'Habitación'} description={selected ? `Piso ${selected.floor} · ${selected.category}` : ''}>{selected ? <div className="detail-stack">
      <DetailGrid items={[{ label: 'Estado', node: <StatusBadge>{selected.status}</StatusBadge> }, { label: 'Tarifa', value: `${formatMoney(selected.nightlyRate)} / noche` }, { label: 'Capacidad y camas', value: `${selected.capacity} persona(s) · ${selected.beds}` }, { label: 'Limpieza', value: selected.cleaningStatus }, { label: 'Check-in real', value: formatDateTime(selected.checkInAt) }, { label: 'Salida prevista', value: selected.expectedCheckOut ? displayCalendarDate(selected.expectedCheckOut) : 'Sin estadía activa' }]} />
      <section><SectionHeader title="Comodidades" /><div className="chip-row">{Object.entries(selected.amenities).filter(([, enabled]) => enabled).map(([key]) => <span className="chip" key={key}>{({ airConditioning: 'Aire acondicionado', television: 'Televisor', hotWater: 'Agua caliente', wifi: 'Wi-Fi', minibar: 'Frigobar' })[key]}</span>)}</div></section>
      <section><SectionHeader title="Huésped y contratación" /><DetailGrid items={[{ label: 'Huésped activo', value: selected.guestId ? selectClientName(state, selected.guestId) : 'Sin huésped activo' }, { label: 'Estadía', value: stay?.id || 'No aplica' }, { label: 'Reserva', value: reservation?.id || 'No aplica' }, { label: 'Cuenta', value: account?.id || 'Sin cuenta activa', detail: `Saldo ${formatMoney(selectAccountBalance(account))}` }]} /></section>
      <section><SectionHeader title="Incidencias activas" description={`${incidents.length} registro(s) asociados a la habitación.`} />{incidents.length ? <div className="record-list">{incidents.map((item) => <article key={item.id}><div><strong>{item.description}</strong><span>{item.id} · {item.responsible}</span></div><StatusBadge>{item.status}</StatusBadge></article>)}</div> : <p>Sin incidencias activas.</p>}</section>
    </div> : null}</Drawer>
  </div>;
}

function ReservationForm({ onClose, notify }) {
  const { state, dispatch } = useHotel();
  const availableRooms = state.rooms.filter((room) => room.status === 'Disponible');
  const [form, setForm] = useState({ clientId: state.clients[0]?.id || '', roomId: availableRooms[0]?.id || '', checkIn: future(1), checkOut: future(3), guests: 1, extraGuests: 0, services: ['Desayuno'], arrivalLimit: '20:00', paymentMethod: 'Yape', operationNumber: '' });
  const room = availableRooms.find((item) => item.id === form.roomId);
  const checkInDate = parseCalendarDate(form.checkIn);
  const checkOutDate = parseCalendarDate(form.checkOut);
  const nights = checkInDate && checkOutDate ? Math.max(1, Math.round((Date.UTC(checkOutDate.getFullYear(), checkOutDate.getMonth(), checkOutDate.getDate()) - Date.UTC(checkInDate.getFullYear(), checkInDate.getMonth(), checkInDate.getDate())) / 86400000)) : 1;
  const lodging = (room?.nightlyRate || 0) * nights;
  const extras = Number(form.extraGuests) * 45 * nights;
  const services = form.services.length * 20;
  const total = lodging + extras + services;
  const toggleService = (service) => setForm({ ...form, services: form.services.includes(service) ? form.services.filter((item) => item !== service) : [...form.services, service] });
  const submit = (event) => {
    event.preventDefault();
    if (!room || form.checkOut <= form.checkIn || Number(form.guests) > room.capacity) { notify('Reserva no válida', 'Revisá disponibilidad, fechas y capacidad de la habitación.', 'error'); return; }
    if (executeWithFeedback(dispatch, { type: 'RESERVATION_CONFIRM', payload: { ...form, guests: Number(form.guests), extraGuests: Number(form.extraGuests) } }, notify, { title: 'Reserva confirmada', message: 'Se registraron adelanto, contrato, documento interno, caja, auditoría y notificación.' })) onClose();
  };
  return <form className="form-grid" onSubmit={submit}>
    <label className="span-2">Cliente<select required value={form.clientId} onChange={(event) => setForm({ ...form, clientId: event.target.value })}>{state.clients.map((client) => <option key={client.id} value={client.id}>{client.name} · {client.documentNumber}</option>)}</select></label>
    <label className="span-2">Habitación disponible<select required value={form.roomId} onChange={(event) => setForm({ ...form, roomId: event.target.value })}>{availableRooms.map((item) => <option key={item.id} value={item.id}>Hab. {item.id} · {item.category} · capacidad {item.capacity} · {formatMoney(item.nightlyRate)}</option>)}</select></label>
    <label>Ingreso<input type="date" required value={form.checkIn} onChange={(event) => setForm({ ...form, checkIn: event.target.value })} /></label><label>Salida<input type="date" required value={form.checkOut} onChange={(event) => setForm({ ...form, checkOut: event.target.value })} /></label>
    <label>Huéspedes contratados<input type="number" min="1" max={room?.capacity || 1} value={form.guests} onChange={(event) => setForm({ ...form, guests: event.target.value })} /></label><label>Personas adicionales<input type="number" min="0" max="4" value={form.extraGuests} onChange={(event) => setForm({ ...form, extraGuests: event.target.value })} /></label>
    <label>Hora límite de llegada<input type="time" required value={form.arrivalLimit} onChange={(event) => setForm({ ...form, arrivalLimit: event.target.value })} /></label><label>Método del adelanto<select value={form.paymentMethod} onChange={(event) => setForm({ ...form, paymentMethod: event.target.value })}>{PAYMENT_METHODS.map((method) => <option key={method}>{method}</option>)}</select></label>
    <fieldset className="span-2 option-fieldset"><legend>Servicios adicionales</legend>{['Desayuno', 'Piscina', 'Mirador', 'Cochera'].map((service) => <label className="check-option" key={service}><input type="checkbox" checked={form.services.includes(service)} onChange={() => toggleService(service)} />{service} · {formatMoney(20)}</label>)}</fieldset>
    <label className="span-2">Número de operación<input value={form.operationNumber} onChange={(event) => setForm({ ...form, operationNumber: event.target.value })} placeholder="Referencia opcional del adelanto" /></label>
    <div className="estimate span-2"><span>Desglose transparente · {nights} noche(s)</span><div className="account-lines"><span>Hospedaje<strong>{formatMoney(lodging)}</strong></span><span>Personas adicionales<strong>{formatMoney(extras)}</strong></span><span>Servicios<strong>{formatMoney(services)}</strong></span></div><strong>Total {formatMoney(total)}</strong><small>Adelanto requerido 50 %: {formatMoney(total / 2)} · saldo: {formatMoney(total / 2)}</small></div>
    <div className="form-actions span-2"><button type="button" className="btn btn-outline" onClick={onClose}>Cancelar</button><button className="btn btn-primary">Confirmar reserva y adelanto</button></div>
  </form>;
}

export function ReservationsView({ notify }) {
  const { state } = useHotel();
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('Todos');
  const [category, setCategory] = useState('Todas');
  const [date, setDate] = useState('');
  const [selectedId, setSelectedId] = useState(null);
  const [open, setOpen] = useState(false);
  const deferred = useDeferredValue(query.toLowerCase());
  const records = state.reservations.filter((item) => `${item.id} ${item.roomId} ${selectClientName(state, item.clientId)}`.toLowerCase().includes(deferred) && (status === 'Todos' || item.status === status) && (category === 'Todas' || item.category === category) && (!date || (item.checkIn <= date && item.checkOut >= date)));
  const selected = state.reservations.find((item) => item.id === selectedId);
  const client = state.clients.find((item) => item.id === selected?.clientId);
  const room = state.rooms.find((item) => item.id === selected?.roomId);
  const payment = state.payments.find((item) => item.reservationId === selected?.id);
  return <div className="view-container">
    <PageHeader metadata="Disponibilidad y adelanto conectados" title="Reservas" description="Consulta completa de contratación, llegada, servicios, pagos y contrato asociado." action={<button className="btn btn-primary" onClick={() => setOpen(true)}>Nueva reserva</button>} />
    <MetricStrip items={[{ label: 'Total', value: state.reservations.length }, { label: 'Confirmadas', value: state.reservations.filter((item) => item.status === 'Confirmada').length }, { label: 'Presentes', value: state.reservations.filter((item) => item.status === 'Cliente presente').length }, { label: 'Adelantos registrados', value: formatMoney(state.reservations.reduce((sum, item) => sum + item.advance, 0)) }, { label: 'Saldo contractual', value: formatMoney(state.reservations.reduce((sum, item) => sum + item.balance, 0)) }]} />
    <div className="filter-bar"><label className="search-label"><Search size={16} /><input aria-label="Buscar reservas" placeholder="Código, cliente o habitación" value={query} onChange={(event) => setQuery(event.target.value)} /></label><label>Estado<select value={status} onChange={(event) => setStatus(event.target.value)}><option>Todos</option>{RESERVATION_STATUSES.map((item) => <option key={item}>{item}</option>)}</select></label><label>Categoría<select value={category} onChange={(event) => setCategory(event.target.value)}><option>Todas</option>{ROOM_CATEGORIES.map((item) => <option key={item}>{item}</option>)}</select></label><label>Fecha incluida<input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><span className="filter-result">{records.length} registros</span></div>
    <DataTable caption="Reservas visibles y estado de contratación" columns={['Reserva', 'Cliente', 'Habitación', 'Estadía y llegada', 'Total / saldo', 'Contrato', 'Estado', 'Detalle']} emptyTitle="Sin reservas" emptyDescription="No hay reservas que coincidan con los filtros.">{records.length ? records.map((item) => <tr key={item.id}><td><strong>{item.id}</strong></td><td>{selectClientName(state, item.clientId)}</td><td>{item.roomId} · {item.category}</td><td>{displayCalendarDate(item.checkIn)} a {displayCalendarDate(item.checkOut)}<br /><small>Límite {item.arrivalLimit}</small></td><td>{formatMoney(item.total)}<br /><small>Saldo {formatMoney(item.balance)}</small></td><td>{item.contractId || 'Pendiente'}</td><td><StatusBadge>{item.status}</StatusBadge></td><td><button className="btn btn-sm btn-outline" onClick={() => setSelectedId(item.id)}>Ver reserva</button></td></tr>) : null}</DataTable>
    <Drawer open={Boolean(selected)} onClose={() => setSelectedId(null)} title={selected?.id || 'Reserva'} description={selected ? `${displayCalendarDate(selected.checkIn)} a ${displayCalendarDate(selected.checkOut)}` : ''}>{selected ? <div className="detail-stack"><DetailGrid items={[{ label: 'Cliente', value: client?.name, detail: `${client?.documentType} ${client?.documentNumber}` }, { label: 'Habitación', value: `${room?.id} · ${selected.category}`, detail: `Piso ${room?.floor}` }, { label: 'Huéspedes', value: `${selected.guests} contratados`, detail: `${selected.extraGuests} adicionales · ${selected.petIds.length} mascota(s)` }, { label: 'Llegada', value: displayCalendarDate(selected.checkIn), detail: `Límite ${selected.arrivalLimit}` }, { label: 'Salida', value: displayCalendarDate(selected.checkOut), detail: `${selected.nights} noche(s)` }, { label: 'Estado', node: <StatusBadge>{selected.status}</StatusBadge> }]} /><section><SectionHeader title="Servicios" /><div className="chip-row">{selected.services.length ? selected.services.map((item) => <span className="chip" key={item}>{item}</span>) : <span className="muted-block">Sin servicios adicionales.</span>}</div></section><section><SectionHeader title="Economía y referencias" /><DetailGrid items={[{ label: 'Hospedaje base', value: formatMoney(selected.nightlyRate * selected.nights) }, { label: 'Total contratado', value: formatMoney(selected.total) }, { label: 'Adelanto 50 %', value: formatMoney(selected.advance), detail: `${selected.paymentMethod} · ${payment?.operationNumber || 'Sin operación'}` }, { label: 'Saldo', value: formatMoney(selected.balance) }, { label: 'Contrato', value: selected.contractId || 'No generado' }, { label: 'Pago', value: payment?.id || 'No registrado' }]} /></section></div> : null}</Drawer>
    <Dialog open={open} onClose={() => setOpen(false)} title="Nueva reserva" description="El prototipo registra un adelanto interno; no procesa dinero real." wide><ReservationForm onClose={() => setOpen(false)} notify={notify} /></Dialog>
  </div>;
}

export function CheckInOutView({ notify }) {
  const { state, dispatch, execute } = useHotel();
  const [tab, setTab] = useState('checkin');
  const [paymentMethod, setPaymentMethod] = useState('Tarjeta');
  const [confirmation, setConfirmation] = useState(null);
  const [verifiedSubjectId, setVerifiedSubjectId] = useState(null);
  const arrivals = state.reservations.filter((item) => item.status === 'Confirmada');
  const activeStays = state.stays.filter((item) => item.status === 'Activa');
  const confirmationReservation = confirmation?.type === 'checkin' ? state.reservations.find((item) => item.id === confirmation.id) : null;
  const confirmationClient = state.clients.find((item) => item.id === confirmationReservation?.clientId);
  const recordBiometricAttempt = (subjectId, attempt) => dispatch({ type: 'BIOMETRIC_ATTEMPT', subjectId, ...attempt });
  const confirm = () => {
    if (confirmation.type === 'checkin') {
      if (verifiedSubjectId !== confirmationClient?.id) {
        notify('Identidad pendiente', 'Verificá una huella coincidente antes de completar el check-in.', 'error');
        return;
      }
      const result = execute({ type: 'CHECK_IN', reservationId: confirmation.id, identityValidation: { method: 'biometric', matched: true, verifiedAt: new Date().toISOString(), responsible: 'Bridge ZK9500' } });
      if (!result.ok) { notify('Check-in rechazado', result.error || result.message || 'No se pudo completar la operación.', 'error'); return; }
      notify('Check-in completado', 'La identidad biométrica coincidió y los registros vinculados se actualizaron atómicamente.');
    } else {
      const result = execute({ type: 'CHECK_OUT', stayId: confirmation.id, paymentMethod, operationNumber: 'CIERRE-DEMO' });
      if (!result.ok) { notify('Check-out rechazado', result.error || result.message || 'No se pudo completar la operación.', 'error'); return; }
      notify('Check-out completado', 'Cuenta cerrada, accesos desactivados y habitación enviada a limpieza.');
    }
    setConfirmation(null);
    setVerifiedSubjectId(null);
  };
  return <div className="view-container">
    <PageHeader metadata="Acciones atómicas con confirmación" title="Check-in y check-out" description="Revisión previa de identidad, contrato, cuenta y consecuencias operativas." />
    <MetricStrip items={[{ label: 'Llegadas listas', value: arrivals.length }, { label: 'Estadías activas', value: activeStays.length }, { label: 'Saldos a liquidar', value: formatMoney(activeStays.reduce((sum, stay) => sum + selectAccountBalance(state.accounts.find((item) => item.id === stay.accountId)), 0)) }, { label: 'Accesos activos', value: state.recreationAccess.filter((item) => ['Habilitado', 'Dentro de piscina'].includes(item.status)).length }]} />
    <Tabs label="Operación de recepción" tabs={[{ id: 'checkin', label: `Llegadas (${arrivals.length})` }, { id: 'checkout', label: `Salidas (${activeStays.length})` }]} activeTab={tab} onChange={setTab} />
    <TabPanel active={tab === 'checkin'} label="Llegadas confirmadas"><div className="operation-cards">{arrivals.length ? arrivals.map((reservation) => { const contract = state.contracts.find((item) => item.id === reservation.contractId); const client = state.clients.find((item) => item.id === reservation.clientId); return <article className="card operation-card" key={reservation.id}><div className="row-between"><div><span className="eyebrow">{reservation.id}</span><h3>{client?.name}</h3></div><StatusBadge>{reservation.status}</StatusBadge></div><DetailGrid compact items={[{ label: 'Identidad', value: `${client?.documentType} ${client?.documentNumber}` }, { label: 'Habitación', value: `${reservation.roomId} · ${reservation.category}` }, { label: 'Contrato', value: contract?.id, detail: contract?.status }, { label: 'Cuenta inicial', value: formatMoney(reservation.total), detail: `Adelanto ${formatMoney(reservation.advance)}` }]} /><div className="checklist"><span><CheckCircle2 size={15} /> Validar documento y huésped</span><span><ClipboardCheck size={15} /> Revisar contrato, servicios, mascotas y políticas</span><span><CreditCard size={15} /> Abrirá cuenta con saldo {formatMoney(reservation.balance)}</span><span><DoorOpen size={15} /> Habitación pasará a Ocupada</span></div><button className="btn btn-primary" onClick={() => { setVerifiedSubjectId(null); setConfirmation({ type: 'checkin', id: reservation.id, title: `Confirmar ingreso de ${client?.name}` }); }}>Revisar y completar check-in</button></article>; }) : <EmptyState title="Sin llegadas confirmadas" />}</div></TabPanel>
    <TabPanel active={tab === 'checkout'} label="Estadías activas"><div className="filter-bar"><label>Método de liquidación<select value={paymentMethod} onChange={(event) => setPaymentMethod(event.target.value)}>{PAYMENT_METHODS.map((method) => <option key={method}>{method}</option>)}</select></label></div><div className="operation-cards">{activeStays.length ? activeStays.map((stay) => { const account = state.accounts.find((item) => item.id === stay.accountId); const accesses = state.recreationAccess.filter((item) => item.stayId === stay.id && !['Finalizado', 'Vencido'].includes(item.status)); return <article className="card operation-card" key={stay.id}><div className="row-between"><div><span className="eyebrow">{stay.id} · Hab. {stay.roomId}</span><h3>{selectClientName(state, stay.clientId)}</h3></div><StatusBadge>{account?.status}</StatusBadge></div><section><SectionHeader title="Cargos" /><div className="account-lines">{account?.charges.map((charge) => <span key={charge.id}>{charge.concept}<strong>{formatMoney(charge.amount)}</strong></span>)}</div></section><section><SectionHeader title="Pagos aplicados" /><div className="account-lines">{account?.payments.length ? account.payments.map((payment) => <span className="payment-line" key={payment.id}>Pago · {payment.method}<strong>− {formatMoney(payment.amount)}</strong></span>) : <span>Sin pagos aplicados<strong>{formatMoney(0)}</strong></span>}</div></section><div className="operation-total"><span>Saldo final</span><strong>{formatMoney(selectAccountBalance(account))}</strong></div><div className="alert-banner alert-banner-warning">Al confirmar: se cierra la cuenta y contrato, se finalizan {accesses.length} acceso(s), y la habitación pasa a limpieza.</div><button className="btn btn-primary" onClick={() => setConfirmation({ type: 'checkout', id: stay.id, title: `Confirmar salida de ${selectClientName(state, stay.clientId)}` })}>Revisar y completar check-out</button></article>; }) : <EmptyState title="Sin estadías activas" />}</div></TabPanel>
    <Dialog open={Boolean(confirmation)} onClose={() => { setConfirmation(null); setVerifiedSubjectId(null); }} title={confirmation?.title || 'Confirmar operación'} description="Esta acción actualiza varios registros relacionados y no puede deshacerse en el prototipo."><div className="detail-stack"><p>{confirmation?.type === 'checkin' ? 'La huella debe coincidir antes de declarar la identidad validada y abrir la estadía.' : `Se liquidará el saldo mediante ${paymentMethod}, se cerrará la estadía y se creará una tarea de limpieza.`}</p>{confirmationClient ? <BiometricPanel subjectType="client" subjectId={confirmationClient.id} subjectName={confirmationClient.name} reference={confirmationClient.biometric?.templateReference} onEnrolled={(result) => dispatch({ type: 'BIOMETRIC_ENROLLED', subjectType: 'client', subjectId: confirmationClient.id, ...result })} onVerified={(result) => setVerifiedSubjectId(result.matched ? confirmationClient.id : null)} onAttempt={(attempt) => recordBiometricAttempt(confirmationClient.id, attempt)} /> : null}{confirmation?.type === 'checkin' ? <div className={`alert-banner ${verifiedSubjectId === confirmationClient?.id ? 'alert-banner-success' : 'alert-banner-warning'}`}>{verifiedSubjectId === confirmationClient?.id ? 'Identidad biométrica verificada para este check-in.' : 'Check-in bloqueado hasta obtener una coincidencia real.'}</div> : null}<div className="form-actions"><button className="btn btn-outline" onClick={() => { setConfirmation(null); setVerifiedSubjectId(null); }}>Volver a revisar</button><button className="btn btn-primary" disabled={confirmation?.type === 'checkin' && verifiedSubjectId !== confirmationClient?.id} onClick={confirm}>Confirmar operación</button></div></div></Dialog>
  </div>;
}

function ClientForm({ onClose, notify }) {
  const { dispatch } = useHotel();
  const [form, setForm] = useState({ documentType: 'DNI', documentNumber: '', firstName: '', lastName: '', phone: '', email: '', address: '', nationality: 'Peruana', birthDate: '', emergencyContact: '', notes: '' });
  const submit = (event) => { event.preventDefault(); if (executeWithFeedback(dispatch, { type: 'CLIENT_CREATE', payload: form }, notify, { title: 'Cliente registrado', message: 'El perfil se agregó al estado de esta sesión.' })) onClose(); };
  return <form className="form-grid" onSubmit={submit}><label>Tipo de documento<select value={form.documentType} onChange={(event) => setForm({ ...form, documentType: event.target.value })}><option>DNI</option><option>Carnet de extranjería</option><option>Pasaporte</option></select></label><label>Número<input required value={form.documentNumber} onChange={(event) => setForm({ ...form, documentNumber: event.target.value })} /></label><label>Nombres<input required value={form.firstName} onChange={(event) => setForm({ ...form, firstName: event.target.value })} /></label><label>Apellidos<input required value={form.lastName} onChange={(event) => setForm({ ...form, lastName: event.target.value })} /></label><label>Teléfono<input value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></label><label>Correo<input type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label><label className="span-2">Dirección<input value={form.address} onChange={(event) => setForm({ ...form, address: event.target.value })} /></label><label>Nacionalidad<input value={form.nationality} onChange={(event) => setForm({ ...form, nationality: event.target.value })} /></label><label>Fecha de nacimiento<input type="date" value={form.birthDate} onChange={(event) => setForm({ ...form, birthDate: event.target.value })} /></label><label className="span-2">Contacto de emergencia<input value={form.emergencyContact} onChange={(event) => setForm({ ...form, emergencyContact: event.target.value })} /></label><label className="span-2">Observaciones<textarea value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></label><div className="form-actions span-2"><button type="button" className="btn btn-outline" onClick={onClose}>Cancelar</button><button className="btn btn-primary">Registrar cliente</button></div></form>;
}

export function CustomersView({ notify }) {
  const { state, dispatch } = useHotel();
  const [query, setQuery] = useState('');
  const [tier, setTier] = useState('Todos');
  const [consent, setConsent] = useState('Todos');
  const [selectedId, setSelectedId] = useState(null);
  const [createOpen, setCreateOpen] = useState(false);
  const deferred = useDeferredValue(query.toLowerCase());
  const clients = state.clients.filter((item) => `${item.name} ${item.documentNumber} ${item.email}`.toLowerCase().includes(deferred) && (tier === 'Todos' || item.loyaltyTier === tier) && (consent === 'Todos' || item.promoAuth === (consent === 'Autorizado')));
  const selected = state.clients.find((item) => item.id === selectedId);
  const reservations = state.reservations.filter((item) => item.clientId === selectedId).toSorted((a, b) => b.checkIn.localeCompare(a.checkIn));
  const stays = state.stays.filter((item) => item.clientId === selectedId);
  const incidents = state.incidents.filter((item) => stays.some((stay) => stay.id === item.referenceId) || reservations.some((reservation) => reservation.roomId === item.roomId));
  const surveys = state.surveys.filter((item) => item.clientId === selectedId);
  const pets = state.pets.filter((item) => item.clientId === selectedId);
  return <div className="view-container">
    <PageHeader metadata="Perfil e historial derivados" title="Clientes y fidelización" description="Contacto, consentimiento, preferencias, estadías, mascotas, incidencias y encuestas vinculadas." action={<button className="btn btn-primary" onClick={() => setCreateOpen(true)}>Registrar cliente</button>} />
    <MetricStrip items={[{ label: 'Perfiles', value: state.clients.length }, { label: 'Frecuentes', value: state.clients.filter((item) => item.visits >= 3).length }, { label: 'Promociones autorizadas', value: state.clients.filter((item) => item.promoAuth).length }, { label: 'Con mascotas', value: state.clients.filter((item) => item.petIds.length).length }]} />
    <div className="filter-bar"><label className="search-label"><Search size={16} /><input aria-label="Buscar clientes" placeholder="Nombre, documento o correo" value={query} onChange={(event) => setQuery(event.target.value)} /></label><label>Fidelización<select value={tier} onChange={(event) => setTier(event.target.value)}><option>Todos</option><option>Bronce</option><option>Plata</option><option>Oro</option></select></label><label>Promociones<select value={consent} onChange={(event) => setConsent(event.target.value)}><option>Todos</option><option>Autorizado</option><option>No autorizado</option></select></label><span className="filter-result">{clients.length} perfiles</span></div>
    <div className="customer-grid">{clients.length ? clients.map((client) => <button className="customer-card" key={client.id} onClick={() => setSelectedId(client.id)}><div className="avatar">{client.firstName[0]}{client.lastName[0]}</div><div><strong>{client.name}</strong><span>{client.documentType} {client.documentNumber}</span><small>{client.visits} estadías declaradas · {formatMoney(client.totalSpent)}</small></div><span className="badge badge-gold">{client.loyaltyTier}</span></button>) : <EmptyState />}</div>
    <Drawer open={Boolean(selected)} onClose={() => setSelectedId(null)} title={selected?.name || 'Cliente'} description={selected ? `${selected.documentType} ${selected.documentNumber}` : ''}>{selected ? <div className="detail-stack">
      <DetailGrid items={[{ label: 'Teléfono', value: selected.phone }, { label: 'Correo', value: selected.email }, { label: 'Dirección', value: selected.address }, { label: 'Nacionalidad', value: selected.nationality }, { label: 'Nacimiento', value: displayCalendarDate(selected.birthDate) }, { label: 'Emergencia', value: selected.emergencyContact }, { label: 'Promociones', value: selected.promoAuth ? 'Autorizadas' : 'No autorizadas' }, { label: 'Observaciones', value: selected.notes || 'Sin observaciones' }]} />
      <BiometricPanel subjectType="client" subjectId={selected.id} subjectName={selected.name} reference={selected.biometric?.templateReference} onEnrolled={(result) => dispatch({ type: 'BIOMETRIC_ENROLLED', subjectType: 'client', subjectId: selected.id, ...result })} onAttempt={(attempt) => dispatch({ type: 'BIOMETRIC_ATTEMPT', subjectId: selected.id, ...attempt })} />
      <section><SectionHeader title="Preferencias y fidelización" /><div className="chip-row">{selected.preferences.map((item) => <span className="chip" key={item}>{item}</span>)}</div><DetailGrid compact items={[{ label: 'Nivel', value: selected.loyaltyTier }, { label: 'Puntos', value: selected.loyaltyPoints }, { label: 'Estadías declaradas', value: selected.visits }, { label: 'Consumo declarado', value: formatMoney(selected.totalSpent) }]} /><button className="btn btn-outline" onClick={() => executeWithFeedback(dispatch, { type: 'CLIENT_UPDATE', clientId: selected.id, changes: { promoAuth: !selected.promoAuth } }, notify, { title: 'Consentimiento actualizado', message: `Promociones ${selected.promoAuth ? 'desautorizadas' : 'autorizadas'} en esta sesión.` })}>Cambiar consentimiento promocional</button></section>
      <section><SectionHeader title="Historial disponible en esta sesión" description={`${reservations.length} reserva(s) · ${stays.length} estadía(s) · ${incidents.length} incidencia(s)`} /><div className="record-list">{reservations.map((item) => <article key={item.id}><div><strong>{item.id} · Hab. {item.roomId}</strong><span>{displayCalendarDate(item.checkIn)} a {displayCalendarDate(item.checkOut)} · {formatMoney(item.total)}</span></div><StatusBadge>{item.status}</StatusBadge></article>)}</div></section>
      <section><SectionHeader title="Mascotas y encuestas" /><DetailGrid items={[{ label: 'Mascotas', value: pets.length ? pets.map((item) => item.name).join(', ') : 'Sin mascotas' }, { label: 'Encuestas', value: `${surveys.length} registro(s)`, detail: surveys.map((item) => `${item.id}: ${item.status}`).join(' · ') || 'Sin respuestas' }, { label: 'Valoración declarada', value: selected.rating ? `${selected.rating} / 5` : 'Sin valoración' }, { label: 'Cancelaciones', value: reservations.filter((item) => item.status === 'Cancelada').length }]} /></section>
    </div> : null}</Drawer>
    <Dialog open={createOpen} onClose={() => setCreateOpen(false)} title="Registrar cliente" description="Datos básicos requeridos por el perfil del huésped." wide><ClientForm onClose={() => setCreateOpen(false)} notify={notify} /></Dialog>
  </div>;
}

export function CleaningView({ notify }) {
  const { state, dispatch } = useHotel();
  const [status, setStatus] = useState('Todos');
  const [selectedId, setSelectedId] = useState(null);
  const records = state.cleaningTasks.filter((item) => status === 'Todos' || item.status === status);
  const selected = state.cleaningTasks.find((item) => item.id === selectedId);
  const room = state.rooms.find((item) => item.id === selected?.roomId);
  const advance = (task) => executeWithFeedback(dispatch, { type: 'CLEANING_PROGRESS', taskId: task.id, expectedStatus: task.status }, notify, { title: 'Limpieza actualizada', message: task.status === 'Completada' ? `La habitación ${task.roomId} fue recalculada según sus bloqueos activos.` : 'La tarea avanzó conservando tiempos y evidencia.' });
  return <div className="view-container">
    <PageHeader metadata="Aprobación libera habitación" title="Limpieza" description="Tareas con responsable, motivo, tiempos, evidencia y consecuencia sobre disponibilidad." />
    <MetricStrip items={['Pendiente', 'En proceso', 'Completada', 'Aprobada'].map((item) => ({ label: item, value: state.cleaningTasks.filter((task) => task.status === item).length }))} />
    <div className="filter-bar"><label>Estado<select value={status} onChange={(event) => setStatus(event.target.value)}><option>Todos</option><option>Pendiente</option><option>En proceso</option><option>Completada</option><option>Aprobada</option></select></label><span className="filter-result">{records.length} tareas</span></div>
    <div className="operation-cards">{records.length ? records.map((task) => <article className="card operation-card" key={task.id}><div className="row-between"><div><span className="eyebrow">{task.id}</span><h3>Habitación {task.roomId}</h3></div><StatusBadge>{task.status}</StatusBadge></div><p>{task.reason}</p><DetailGrid compact items={[{ label: 'Responsable', value: task.assignedTo }, { label: 'Estado habitación', value: state.rooms.find((item) => item.id === task.roomId)?.status }, { label: 'Inicio', value: formatDateTime(task.startedAt) }, { label: 'Fin', value: formatDateTime(task.completedAt) }]} /><div className="inline-actions"><button className="btn btn-sm btn-outline" onClick={() => setSelectedId(task.id)}>Ver detalle</button>{task.status !== 'Aprobada' ? <button className="btn btn-sm btn-primary" onClick={() => advance(task)}>{task.status === 'Pendiente' ? 'Iniciar' : task.status === 'En proceso' ? 'Completar con evidencia' : 'Aprobar y liberar'}</button> : null}</div></article>) : <EmptyState />}</div>
    <Drawer open={Boolean(selected)} onClose={() => setSelectedId(null)} title={selected?.id || 'Tarea'} description={selected ? `Habitación ${selected.roomId}` : ''}>{selected ? <div className="detail-stack"><DetailGrid items={[{ label: 'Estado', node: <StatusBadge>{selected.status}</StatusBadge> }, { label: 'Responsable', value: selected.assignedTo }, { label: 'Motivo', value: selected.reason }, { label: 'Habitación', value: room?.status, detail: selected.status === 'Aprobada' ? 'Disponible después de aprobación' : 'No reservable mientras continúe la tarea' }, { label: 'Inicio', value: formatDateTime(selected.startedAt) }, { label: 'Finalización', value: formatDateTime(selected.completedAt) }]} /><section><SectionHeader title="Evidencia declarada" />{selected.evidence.length ? <ul className="detail-list">{selected.evidence.map((item) => <li key={item}>{item}</li>)}</ul> : <p>Sin referencias de evidencia. Los archivos no se almacenan en este frontend.</p>}</section></div> : null}</Drawer>
  </div>;
}

function MaintenanceForm({ onClose, notify }) {
  const { state, dispatch } = useHotel();
  const [form, setForm] = useState({ roomId: state.rooms[0].id, type: 'Aire acondicionado', description: '', priority: 'Media', assignedTo: 'Por asignar', severe: false, evidence: '' });
  const submit = (event) => { event.preventDefault(); if (executeWithFeedback(dispatch, { type: 'MAINTENANCE_CREATE', payload: form }, notify, { title: 'Ticket creado', message: form.severe ? 'La habitación quedó fuera de servicio y se creó una incidencia vinculada.' : 'El ticket y su incidencia quedaron vinculados.' })) onClose(); };
  return <form className="form-grid" onSubmit={submit}><label>Habitación<select value={form.roomId} onChange={(event) => setForm({ ...form, roomId: event.target.value })}>{state.rooms.map((room) => <option key={room.id} value={room.id}>{room.id} · {room.status}</option>)}</select></label><label>Tipo<select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}>{['Aire acondicionado', 'Electricidad', 'Agua', 'Televisión', 'Wi-Fi', 'Cerraduras', 'Puertas', 'Baños', 'Muebles', 'Otros equipos'].map((item) => <option key={item}>{item}</option>)}</select></label><label>Prioridad<select value={form.priority} onChange={(event) => setForm({ ...form, priority: event.target.value })}><option>Baja</option><option>Media</option><option>Alta</option><option>Urgente</option></select></label><label>Responsable<input value={form.assignedTo} onChange={(event) => setForm({ ...form, assignedTo: event.target.value })} /></label><label className="span-2">Descripción<textarea required value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><label className="span-2">Referencia de evidencia<input value={form.evidence} onChange={(event) => setForm({ ...form, evidence: event.target.value })} placeholder="Referencia declarada; no adjunta archivos" /></label><label className="toggle-row span-2"><input type="checkbox" checked={form.severe} onChange={(event) => setForm({ ...form, severe: event.target.checked })} /><span>Falla grave: sacar habitación de servicio</span></label>{form.severe ? <div className="alert-banner alert-banner-danger span-2">La creación marcará la habitación como Fuera de servicio y agregará la incidencia a su detalle.</div> : null}<div className="form-actions span-2"><button type="button" className="btn btn-outline" onClick={onClose}>Cancelar</button><button className="btn btn-primary">Crear ticket</button></div></form>;
}

export function MaintenanceView({ notify }) {
  const { state } = useHotel();
  const [open, setOpen] = useState(false);
  const [priority, setPriority] = useState('Todas');
  const [status, setStatus] = useState('Todos');
  const [roomId, setRoomId] = useState('Todas');
  const records = state.maintenanceTickets.filter((item) => (priority === 'Todas' || item.priority === priority) && (status === 'Todos' || item.status === status) && (roomId === 'Todas' || item.roomId === roomId));
  return <div className="view-container">
    <PageHeader metadata="Tickets vinculados a incidencias" title="Mantenimiento" description="Severidad, evidencia, responsable, solución y efecto sobre la habitación." action={<button className="btn btn-primary" onClick={() => setOpen(true)}>Reportar problema</button>} />
    <MetricStrip items={[{ label: 'Tickets', value: state.maintenanceTickets.length }, { label: 'Urgentes', value: state.maintenanceTickets.filter((item) => item.priority === 'Urgente').length }, { label: 'En reparación', value: state.maintenanceTickets.filter((item) => item.status === 'En reparación').length }, { label: 'Fuera de servicio', value: state.rooms.filter((item) => item.status === 'Fuera de servicio').length }]} />
    <div className="filter-bar"><label>Prioridad<select value={priority} onChange={(event) => setPriority(event.target.value)}><option>Todas</option><option>Baja</option><option>Media</option><option>Alta</option><option>Urgente</option></select></label><label>Estado<select value={status} onChange={(event) => setStatus(event.target.value)}><option>Todos</option><option>Reportado</option><option>Asignado</option><option>En reparación</option><option>Solucionado</option><option>Cerrado</option></select></label><label>Habitación<select value={roomId} onChange={(event) => setRoomId(event.target.value)}><option>Todas</option>{[...new Set(state.maintenanceTickets.map((item) => item.roomId))].map((item) => <option key={item}>{item}</option>)}</select></label><span className="filter-result">{records.length} tickets</span></div>
    <div className="operation-cards">{records.length ? records.map((ticket) => { const incident = state.incidents.find((item) => item.referenceId === ticket.id); const room = state.rooms.find((item) => item.id === ticket.roomId); return <article className="card operation-card" key={ticket.id}><div className="row-between"><div><span className="eyebrow">{ticket.id} · Hab. {ticket.roomId}</span><h3>{ticket.type}</h3></div><StatusBadge>{ticket.priority}</StatusBadge></div><p>{ticket.description}</p><DetailGrid compact items={[{ label: 'Responsable', value: ticket.assignedTo }, { label: 'Habitación', value: room?.status }, { label: 'Incidencia', value: incident?.id || 'No encontrada', detail: incident?.status }, { label: 'Evidencia', value: `${ticket.evidence.length} referencia(s)` }, { label: 'Solución', value: ticket.solution || 'Pendiente' }, { label: 'Severa', value: ticket.severe ? 'Sí' : 'No' }]} /><StatusBadge>{ticket.status}</StatusBadge>{ticket.severe ? <div className="alert-banner alert-banner-danger">La falla grave mantiene la habitación fuera de servicio hasta resolución operativa.</div> : null}</article>; }) : <EmptyState />}</div>
    <Dialog open={open} onClose={() => setOpen(false)} title="Nuevo ticket de mantenimiento" description="Una falla grave bloquea la habitación y crea una incidencia unificada."><MaintenanceForm onClose={() => setOpen(false)} notify={notify} /></Dialog>
  </div>;
}

export function OrdersView({ notify, sourceFilter = null, title = 'Pedidos QR', description = 'Seguimiento operativo de cocina, entrega, inventario y pago.' }) {
  const { state, dispatch } = useHotel();
  const [status, setStatus] = useState('Todos');
  const [source, setSource] = useState(sourceFilter || 'Todas');
  const [payment, setPayment] = useState('Todos');
  const records = state.orders.filter((item) => (sourceFilter ? item.source === sourceFilter : source === 'Todas' || item.source === source) && (status === 'Todos' || item.status === status) && (payment === 'Todos' || item.paymentMethod === payment));
  const advance = (order) => { const next = ORDER_STATUSES[ORDER_STATUSES.indexOf(order.status) + 1]; executeWithFeedback(dispatch, { type: 'ORDER_ADVANCE', orderId: order.id, expectedStatus: order.status, operationNumber: `OP-${order.id}` }, notify, { title: 'Pedido actualizado', message: `${next}. Inventario y contabilidad se aplican una sola vez.` }); };
  return <div className="view-container">
    <PageHeader metadata={sourceFilter ? `Origen ${sourceFilter}` : 'Habitación · Barra · Terraza'} title={title} description={description} />
    <MetricStrip items={[{ label: 'Visibles', value: records.length }, { label: 'En preparación', value: records.filter((item) => item.status === 'En preparación').length }, { label: 'Listos', value: records.filter((item) => item.status === 'Listo').length }, { label: 'Pendientes de pago', value: records.filter((item) => item.accountingStage === 'Pendiente de pago').length }, { label: 'Cancelados visibles', value: records.filter((item) => item.status === 'Cancelado').length }]} />
    <div className="filter-bar">{!sourceFilter ? <label>Origen<select value={source} onChange={(event) => setSource(event.target.value)}><option>Todas</option><option>Habitación</option><option>Barra</option><option>Terraza</option></select></label> : null}<label>Estado<select value={status} onChange={(event) => setStatus(event.target.value)}><option>Todos</option>{ORDER_STATUSES.map((item) => <option key={item}>{item}</option>)}</select></label><label>Pago<select value={payment} onChange={(event) => setPayment(event.target.value)}><option>Todos</option>{[...new Set(state.orders.map((item) => item.paymentMethod))].map((item) => <option key={item}>{item}</option>)}</select></label><span className="filter-result">{records.length} pedidos</span></div>
    <div className="order-record-grid">{records.length ? records.map((order) => { const stay = getStay(state, order.stayId); const reservation = getReservation(state, stay?.reservationId); const requirements = getOrderRequirements(state, order); const shortages = order.status === 'Confirmado' && order.inventoryStage === 'Sin reservar' ? getOrderShortages(state, order) : []; const next = ORDER_STATUSES[ORDER_STATUSES.indexOf(order.status) + 1]; return <article className={`card order-record status-border-${statusClass(order.status)}`} key={order.id}><div className="row-between"><div><span className="eyebrow">{order.id} · {order.source}{order.roomId ? ` · Hab. ${order.roomId}` : ''}</span><h3>{order.items.map((item) => item.name).join(', ')}</h3></div><StatusBadge>{order.status}</StatusBadge></div><DetailGrid compact items={[{ label: 'Cliente / estadía', value: stay ? selectClientName(state, stay.clientId) : 'Venta sin estadía', detail: stay ? `${stay.id} · ${reservation?.id}` : 'No se carga a habitación' }, { label: 'ETA declarada', value: `${order.estimatedMinutes} min` }, { label: 'Pago', value: order.paymentMethod, detail: order.accountingStage }, { label: 'Inventario', value: order.inventoryStage }]} /><section><SectionHeader title="Detalle del pedido" /><div className="account-lines">{order.items.map((item) => <span key={`${item.recipeId}-${item.name}`}>{item.quantity} × {item.name}<strong>{formatMoney(item.quantity * item.price)}</strong></span>)}</div><div className="operation-total"><span>Total</span><strong>{formatMoney(order.total)}</strong></div></section><p><strong>Comentario:</strong> {order.comment || 'Sin comentarios'}</p><div className="chip-row">{requirements.map((requirement, index) => { const item = state.inventory.find((entry) => entry.id === requirement.inventoryId); return <span className="chip" key={`${requirement.inventoryId}-${index}`}>{item?.name}: {requirement.quantity} {item?.unit}</span>; })}</div>{shortages.length ? <div className="alert-banner alert-banner-danger">Faltantes: {shortages.map((item) => `${item.name} (${item.available}/${item.required} ${item.unit})`).join(', ')}</div> : null}<div className="inline-actions">{!['Pagado', 'Cancelado'].includes(order.status) ? <button className="btn btn-sm btn-primary" disabled={shortages.length > 0} onClick={() => advance(order)}>{next === 'Pagado' ? order.paymentMethod === 'Cargar a la habitación' ? 'Cerrar pedido' : 'Registrar pago' : `Avanzar a ${next}`}</button> : null}{['Pedido recibido', 'Confirmado', 'En preparación'].includes(order.status) ? <button className="btn btn-sm btn-outline" onClick={() => { dispatch({ type: 'ORDER_CANCEL', orderId: order.id, expectedStatus: order.status }); notify('Pedido cancelado', 'Las reservas de inventario se liberaron cuando correspondía.', 'warning'); }}>Cancelar pedido</button> : null}</div></article>; }) : <EmptyState />}</div>
    <PrototypeNotice>los pedidos cancelados permanecen visibles. Los QR, pasarelas y dispositivos externos no están integrados.</PrototypeNotice>
  </div>;
}

export function BarQrView(props) { return <OrdersView {...props} sourceFilter="Barra" title="QR de la barra" description="Pedidos de barra con ETA, receta, inventario, pago y estado completo." />; }
export function TerraceQrView(props) { return <OrdersView {...props} sourceFilter="Terraza" title="QR de la terraza" description="Pedidos de terraza con el mismo seguimiento operativo y contable." />; }

function InventoryAdjustment({ item, onClose, notify }) {
  const { dispatch } = useHotel();
  const [quantity, setQuantity] = useState(0);
  const [reason, setReason] = useState('Conteo físico');
  const submit = (event) => { event.preventDefault(); if (!Number(quantity) || !reason.trim()) { notify('Ajuste no válido', 'Indicá una cantidad distinta de cero y un motivo.', 'error'); return; } if (executeWithFeedback(dispatch, { type: 'INVENTORY_ADJUST', itemId: item.id, quantity: Number(quantity), reason: reason.trim() }, notify, { title: 'Inventario ajustado', message: `${item.name}: ${Number(quantity) > 0 ? '+' : ''}${quantity} ${item.unit}.` })) onClose(); };
  return <form className="form-grid" onSubmit={submit}><DetailGrid items={[{ label: 'Producto', value: item.name }, { label: 'Físico actual', value: `${item.stock} ${item.unit}` }, { label: 'Reservado', value: `${item.reserved} ${item.unit}` }, { label: 'Disponible', value: `${inventoryAvailable(item)} ${item.unit}`, detail: inventoryAvailable(item) < 0 ? 'Alerta: inventario sobre-reservado' : undefined }]} /><label className="span-2">Cantidad del ajuste<input type="number" step="any" required value={quantity} onChange={(event) => setQuantity(event.target.value)} /><small>Usá negativo para disminuir y positivo para aumentar el stock físico.</small></label><label className="span-2">Motivo<select value={reason} onChange={(event) => setReason(event.target.value)}><option>Conteo físico</option><option>Ingreso</option><option>Merma</option><option>Vencimiento</option><option>Devolución</option><option>Diferencia de inventario</option></select></label><div className="form-actions span-2"><button type="button" className="btn btn-outline" onClick={onClose}>Cancelar</button><button className="btn btn-primary">Registrar ajuste</button></div></form>;
}

export function InventoryView({ notify }) {
  const { state } = useHotel();
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('Todas');
  const [condition, setCondition] = useState('Todos');
  const [supplierId, setSupplierId] = useState('Todos');
  const [selectedId, setSelectedId] = useState(null);
  const expirationLimit = future(7);
  const records = state.inventory.filter((item) => `${item.name} ${item.lot}`.toLowerCase().includes(query.toLowerCase()) && (category === 'Todas' || item.category === category) && (supplierId === 'Todos' || item.supplierId === supplierId) && (condition === 'Todos' || (condition === 'Bajo mínimo' && inventoryAvailable(item) <= item.minimum) || (condition === 'Próximo a vencer' && item.expiresAt && item.expiresAt <= expirationLimit) || (condition === 'Con reserva' && item.reserved > 0)));
  const selected = state.inventory.find((item) => item.id === selectedId);
  const availableValue = state.inventory.reduce((sum, item) => sum + inventoryAvailable(item) * item.cost, 0);
  return <div className="view-container">
    <PageHeader metadata="Físico − reservado = disponible" title="Inventario" description="Existencia física, compromiso de recetas, disponibilidad real, lotes, vencimiento, costo y proveedor." />
    <MetricStrip items={[{ label: 'Productos', value: state.inventory.length }, { label: 'Disponible bajo mínimo', value: state.inventory.filter((item) => inventoryAvailable(item) <= item.minimum).length }, { label: 'Próximos a vencer', value: state.inventory.filter((item) => item.expiresAt && item.expiresAt <= expirationLimit).length }, { label: 'Con stock reservado', value: state.inventory.filter((item) => item.reserved > 0).length }, { label: 'Valor disponible', value: formatMoney(availableValue) }]} />
    <div className="filter-bar"><label className="search-label"><Search size={16} /><input aria-label="Buscar inventario" placeholder="Producto o lote" value={query} onChange={(event) => setQuery(event.target.value)} /></label><label>Categoría<select value={category} onChange={(event) => setCategory(event.target.value)}><option>Todas</option>{[...new Set(state.inventory.map((item) => item.category))].map((item) => <option key={item}>{item}</option>)}</select></label><label>Condición<select value={condition} onChange={(event) => setCondition(event.target.value)}><option>Todos</option><option>Bajo mínimo</option><option>Próximo a vencer</option><option>Con reserva</option></select></label><label>Proveedor<select value={supplierId} onChange={(event) => setSupplierId(event.target.value)}><option>Todos</option>{state.suppliers.map((item) => <option key={item.id} value={item.id}>{item.businessName}</option>)}</select></label><span className="filter-result">{records.length} productos</span></div>
    <DataTable caption="Existencia física, reservada y disponible por producto" columns={['Producto', 'Categoría', 'Físico', 'Reservado', 'Disponible', 'Mínimo', 'Lote / vencimiento', 'Proveedor', 'Urgencia', 'Acción']} emptyTitle="Sin productos">{records.length ? records.map((item) => { const available = inventoryAvailable(item); const supplier = state.suppliers.find((entry) => entry.id === item.supplierId); const overReserved = available < 0; const low = available <= item.minimum; const expiring = item.expiresAt && item.expiresAt <= expirationLimit; return <tr key={item.id}><td><strong>{item.name}</strong><br /><small>{item.id} · {formatMoney(item.cost)} / {item.unit}</small></td><td>{item.category}</td><td>{item.stock} {item.unit}</td><td>{item.reserved} {item.unit}</td><td><strong>{available} {item.unit}</strong></td><td>{item.minimum} {item.unit}</td><td>{item.lot}<br /><small>{item.expiresAt ? displayCalendarDate(item.expiresAt) : 'Sin vencimiento'}</small></td><td>{supplier?.businessName || 'Sin proveedor'}</td><td><StatusBadge>{overReserved ? 'Crítico' : low ? 'Bajo mínimo' : expiring ? 'Pendiente' : 'Óptimo'}</StatusBadge><br /><small>{overReserved ? 'Sobre-reservado: corregir reservas' : low ? 'Reponer disponible' : expiring ? 'Priorizar uso' : 'Sin alerta'}</small></td><td><button className="btn btn-sm btn-outline" onClick={() => setSelectedId(item.id)}>Ajustar</button></td></tr>; }) : null}</DataTable>
    <Dialog open={Boolean(selected)} onClose={() => setSelectedId(null)} title={selected ? `Ajustar ${selected.name}` : 'Ajustar inventario'} description="El ajuste modifica existencia física; las reservas se conservan.">{selected ? <InventoryAdjustment item={selected} onClose={() => setSelectedId(null)} notify={notify} /> : null}</Dialog>
  </div>;
}

export function ParkingView() {
  const { state } = useHotel();
  const [query, setQuery] = useState('');
  const [type, setType] = useState('Todos');
  const [status, setStatus] = useState('Todos');
  const records = state.vehicles.filter((item) => `${item.plate} ${item.brandModel} ${selectClientName(state, item.clientId)} ${item.roomId}`.toLowerCase().includes(query.toLowerCase()) && (type === 'Todos' || item.type === type) && (status === 'Todos' || item.status === status));
  return <div className="view-container"><PageHeader metadata="Vehículo · estadía · espacio" title="Cochera" description="Relación operativa entre huésped, habitación, ingreso, salida, espacio y tarifa." /><MetricStrip items={[{ label: 'Dentro', value: state.vehicles.filter((item) => item.status === 'Dentro').length }, { label: 'Espacios ocupados', value: new Set(state.vehicles.filter((item) => item.status === 'Dentro').map((item) => item.space)).size }, { label: 'Motos gratuitas', value: state.vehicles.filter((item) => item.type === 'Moto' && item.fee === 0).length }, { label: 'Cargos registrados', value: formatMoney(state.vehicles.reduce((sum, item) => sum + item.fee, 0)) }]} /><div className="filter-bar"><label className="search-label"><Search size={16} /><input aria-label="Buscar cochera" placeholder="Placa, vehículo, huésped o habitación" value={query} onChange={(event) => setQuery(event.target.value)} /></label><label>Tipo<select value={type} onChange={(event) => setType(event.target.value)}><option>Todos</option><option>Moto</option><option>Motokar</option><option>Auto</option></select></label><label>Estado<select value={status} onChange={(event) => setStatus(event.target.value)}><option>Todos</option><option>Dentro</option><option>Fuera</option></select></label></div><DataTable caption="Vehículos y relación con la estadía" columns={['Placa', 'Vehículo', 'Huésped', 'Estadía / habitación', 'Espacio', 'Ingreso', 'Salida', 'Tarifa', 'Estado']} emptyTitle="Sin vehículos">{records.length ? records.map((item) => <tr key={item.id}><td><strong>{item.plate}</strong><br /><small>{item.id}</small></td><td>{item.type} · {item.brandModel}</td><td>{selectClientName(state, item.clientId)}</td><td>{item.stayId} · Hab. {item.roomId}</td><td>{item.space}</td><td>{formatDateTime(item.entryAt)}</td><td>{formatDateTime(item.exitAt)}</td><td>{formatMoney(item.fee)}</td><td><StatusBadge>{item.status}</StatusBadge></td></tr>) : null}</DataTable></div>;
}

const EVENT_SERVICES = ['Comida', 'Bebidas', 'Decoración', 'Catering', 'Equipos de sonido', 'Mesas', 'Sillas', 'Coffee break', 'Proyector', 'Otros servicios'];

function EventForm({ onClose, notify }) {
  const { state, dispatch } = useHotel();
  const [form, setForm] = useState({ clientId: state.clients[0].id, title: '', date: future(5), startTime: '18:00', endTime: '22:00', venue: 'Terraza', attendees: 30, services: ['Catering'], total: 1000 });
  const collisions = state.events.filter((item) => item.date === form.date && item.venue === form.venue && form.startTime < item.endTime && form.endTime > item.startTime);
  const toggleService = (service) => setForm({ ...form, services: form.services.includes(service) ? form.services.filter((item) => item !== service) : [...form.services, service] });
  const submit = (event) => { event.preventDefault(); if (collisions.length) { notify('Conflicto de horario', 'El espacio ya tiene un evento superpuesto.', 'error'); return; } if (form.endTime <= form.startTime) { notify('Horario inválido', 'La hora final debe ser posterior a la inicial.', 'error'); return; } if (executeWithFeedback(dispatch, { type: 'EVENT_CREATE', payload: { ...form, attendees: Number(form.attendees), total: Number(form.total) } }, notify, { title: 'Evento registrado', message: 'El horario quedó reservado sin superposición visible.' })) onClose(); };
  return <form className="form-grid" onSubmit={submit}><label className="span-2">Nombre y tipo de evento<input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="Cumpleaños, matrimonio, reunión..." /></label><label>Cliente<select value={form.clientId} onChange={(event) => setForm({ ...form, clientId: event.target.value })}>{state.clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label>Espacio<select value={form.venue} onChange={(event) => setForm({ ...form, venue: event.target.value })}><option>Terraza</option><option>Bar</option><option>Salón Plaza</option></select></label><label>Fecha<input type="date" required value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} /></label><label>Asistentes<input type="number" min="1" value={form.attendees} onChange={(event) => setForm({ ...form, attendees: event.target.value })} /></label><label>Inicio<input type="time" required value={form.startTime} onChange={(event) => setForm({ ...form, startTime: event.target.value })} /></label><label>Fin<input type="time" required value={form.endTime} onChange={(event) => setForm({ ...form, endTime: event.target.value })} /></label><fieldset className="span-2 option-fieldset"><legend>Servicios solicitados</legend>{EVENT_SERVICES.map((service) => <label className="check-option" key={service}><input type="checkbox" checked={form.services.includes(service)} onChange={() => toggleService(service)} />{service}</label>)}</fieldset><label className="span-2">Total estimado<input type="number" min="0" value={form.total} onChange={(event) => setForm({ ...form, total: event.target.value })} /></label>{collisions.length ? <div className="alert-banner alert-banner-danger span-2">Superposición detectada con {collisions.map((item) => `${item.id} (${item.startTime}–${item.endTime})`).join(', ')}.</div> : <div className="alert-banner alert-banner-success span-2">Sin superposición visible para este espacio y horario.</div>}<div className="form-actions span-2"><button type="button" className="btn btn-outline" onClick={onClose}>Cancelar</button><button className="btn btn-primary" disabled={collisions.length > 0}>Comprobar y registrar</button></div></form>;
}

export function EventsView({ notify }) {
  const { state } = useHotel();
  const [open, setOpen] = useState(false);
  const [status, setStatus] = useState('Todos');
  const [venue, setVenue] = useState('Todos');
  const [from, setFrom] = useState('');
  const records = state.events.filter((item) => (status === 'Todos' || item.status === status) && (venue === 'Todos' || item.venue === venue) && (!from || item.date >= from)).toSorted((a, b) => `${a.date}${a.startTime}`.localeCompare(`${b.date}${b.startTime}`));
  return <div className="view-container"><PageHeader metadata="Agenda con validación de solapamiento" title="Eventos" description="Contratación, servicios, asistentes, espacio, adelanto, saldo y estado financiero." action={<button className="btn btn-primary" onClick={() => setOpen(true)}>Nuevo evento</button>} /><MetricStrip items={[{ label: 'Eventos', value: state.events.length }, { label: 'Confirmados', value: state.events.filter((item) => item.status === 'Confirmado').length }, { label: 'Total contratado', value: formatMoney(state.events.reduce((sum, item) => sum + item.total, 0)) }, { label: 'Adelantos', value: formatMoney(state.events.reduce((sum, item) => sum + item.advance, 0)) }, { label: 'Saldo', value: formatMoney(state.events.reduce((sum, item) => sum + item.total - item.advance, 0)) }]} /><div className="filter-bar"><label>Estado<select value={status} onChange={(event) => setStatus(event.target.value)}><option>Todos</option><option>Tentativo</option><option>Confirmado</option><option>Cancelado</option></select></label><label>Espacio<select value={venue} onChange={(event) => setVenue(event.target.value)}><option>Todos</option><option>Terraza</option><option>Bar</option><option>Salón Plaza</option></select></label><label>Desde<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><span className="filter-result">{records.length} eventos</span></div><div className="operation-cards">{records.map((item) => <article className="card operation-card" key={item.id}><div className="row-between"><div><span className="eyebrow">{item.id} · {item.venue}</span><h3>{item.title}</h3></div><StatusBadge>{item.status}</StatusBadge></div><DetailGrid compact items={[{ label: 'Fecha y horario', value: item.date, detail: `${item.startTime}–${item.endTime}` }, { label: 'Cliente', value: selectClientName(state, item.clientId) }, { label: 'Asistentes', value: item.attendees }, { label: 'Total', value: formatMoney(item.total) }, { label: 'Adelanto', value: formatMoney(item.advance) }, { label: 'Saldo', value: formatMoney(item.total - item.advance) }]} /><div className="chip-row">{item.services.map((service) => <span className="chip" key={service}>{service}</span>)}</div></article>)}</div><Dialog open={open} onClose={() => setOpen(false)} title="Programar evento" description="La validación evita solapamientos visibles del mismo espacio." wide><EventForm onClose={() => setOpen(false)} notify={notify} /></Dialog></div>;
}

export function EventCalendarView() {
  const { state } = useHotel();
  const dates = [...new Set(state.events.map((item) => item.date))].toSorted();
  return <div className="view-container"><PageHeader metadata="Agenda agrupada por fecha" title="Calendario de eventos" description="Ocupación por jornada y espacio, con horario, cliente, tipo, servicios y estado." /><MetricStrip items={[{ label: 'Fechas ocupadas', value: dates.length }, { label: 'Eventos programados', value: state.events.length }, { label: 'Espacios usados', value: new Set(state.events.map((item) => item.venue)).size }, { label: 'Asistentes previstos', value: state.events.reduce((sum, item) => sum + item.attendees, 0) }]} /><div className="calendar-agenda">{dates.map((date) => { const events = state.events.filter((item) => item.date === date).toSorted((a, b) => a.startTime.localeCompare(b.startTime)); const venues = [...new Set(events.map((item) => item.venue))]; return <section className="card agenda-day" key={date}><header><time dateTime={date}><strong>{displayCalendarDate(date, { weekday: 'long', day: '2-digit', month: 'long' })}</strong><span>{events.length} evento(s) · {venues.length} espacio(s) ocupado(s)</span></time><div className="chip-row">{venues.map((item) => <span className="chip" key={item}>{item}: {events.filter((event) => event.venue === item).length}</span>)}</div></header><div className="agenda-events">{events.map((item) => <article key={item.id}><time>{item.startTime}<small>{item.endTime}</small></time><div><span className="eyebrow">{item.venue} · {item.id}</span><h3>{item.title}</h3><p>{selectClientName(state, item.clientId)} · {item.attendees} asistentes</p><small>{item.services.join(', ')}</small></div><StatusBadge>{item.status}</StatusBadge></article>)}</div></section>; })}</div></div>;
}

export function StaffView() {
  const { state } = useHotel();
  const [area, setArea] = useState('Todas');
  const [status, setStatus] = useState('Todos');
  const [attendance, setAttendance] = useState('Todos');
  const records = state.staff.filter((item) => (area === 'Todas' || item.area === area) && (status === 'Todos' || item.status === status) && (attendance === 'Todos' || (attendance === 'Registrada' ? item.attendance.startsWith('Ingreso') : item.attendance === 'Pendiente')));
  return <div className="view-container"><PageHeader metadata="Directorio · asistencia · turnos" title="Personal" description="Información laboral, área, contacto, turno, asistencia declarada, horas extra y sueldo." /><MetricStrip items={[{ label: 'Personal activo', value: state.staff.filter((item) => item.status === 'Activo').length }, { label: 'Áreas cubiertas', value: new Set(state.staff.map((item) => item.area)).size }, { label: 'Nómina referencial', value: formatMoney(state.staff.reduce((sum, item) => sum + item.salary, 0)) }, { label: 'Horas extra', value: `${state.staff.reduce((sum, item) => sum + item.overtimeHours, 0)} h` }, { label: 'Asistencia pendiente', value: state.staff.filter((item) => item.attendance === 'Pendiente').length }]} /><div className="filter-bar"><label>Área<select value={area} onChange={(event) => setArea(event.target.value)}><option>Todas</option>{[...new Set(state.staff.map((item) => item.area))].map((item) => <option key={item}>{item}</option>)}</select></label><label>Estado<select value={status} onChange={(event) => setStatus(event.target.value)}><option>Todos</option><option>Activo</option><option>Inactivo</option></select></label><label>Asistencia<select value={attendance} onChange={(event) => setAttendance(event.target.value)}><option>Todos</option><option>Registrada</option><option>Pendiente</option></select></label><span className="filter-result">{records.length} trabajadores</span></div><div className="staff-card-grid">{records.map((person) => <article className="card staff-card" key={person.id}><div className="row-between"><div><span className="eyebrow">{person.id} · DNI {person.documentNumber}</span><h3>{person.name}</h3><p>{person.role} · {person.area}</p></div><StatusBadge>{person.status}</StatusBadge></div><DetailGrid compact items={[{ label: 'Teléfono', value: person.phone }, { label: 'Correo', value: person.email }, { label: 'Turno', value: person.shift }, { label: 'Asistencia', value: person.attendance }, { label: 'Horas extra', value: `${person.overtimeHours} h` }, { label: 'Sueldo', value: formatMoney(person.salary) }]} /></article>)}</div><PrototypeNotice>la asistencia es declarativa. No hay lector de huella o QR conectado ni cálculo real de planilla.</PrototypeNotice></div>;
}

export function CashView() {
  const { state } = useHotel();
  const [type, setType] = useState('Todos');
  const [method, setMethod] = useState('Todos');
  const session = state.cashSessions[0];
  const income = state.cashMovements.filter((item) => item.type === 'Ingreso').reduce((sum, item) => sum + item.amount, 0);
  const expenses = state.cashMovements.filter((item) => item.type === 'Egreso').reduce((sum, item) => sum + item.amount, 0);
  const expected = session.openingAmount + income - expenses;
  const records = state.cashMovements.filter((item) => (type === 'Todos' || item.type === type) && (method === 'Todos' || item.method === method)).toSorted((a, b) => b.createdAt.localeCompare(a.createdAt));
  const methods = [...new Set(state.cashMovements.map((item) => item.method))];
  return <div className="view-container"><PageHeader metadata={`Sesión ${session.id} · ${session.status}`} title="Caja" description="Apertura, movimientos, referencias, ingresos por método, egresos y efectivo esperado." /><MetricStrip items={[{ label: 'Fondo inicial', value: formatMoney(session.openingAmount) }, { label: 'Ingresos', value: formatMoney(income) }, { label: 'Egresos', value: formatMoney(expenses) }, { label: 'Esperado', value: formatMoney(expected) }, { label: 'Movimientos', value: state.cashMovements.length }]} /><div className="operations-grid"><section className="card"><SectionHeader eyebrow="Sesión actual" title="Metadatos de apertura" /><DetailGrid items={[{ label: 'Responsable', value: session.responsible }, { label: 'Apertura', value: formatDateTime(session.openedAt) }, { label: 'Cierre', value: formatDateTime(session.closedAt) }, { label: 'Conteo', value: session.countedAmount == null ? 'Pendiente' : formatMoney(session.countedAmount) }, { label: 'Observaciones', value: session.notes }, { label: 'Estado', node: <StatusBadge>{session.status}</StatusBadge> }]} /></section><section className="card"><SectionHeader eyebrow="Composición" title="Ingresos por método" /><div className="summary-list static">{methods.map((item) => <span key={item}>{item}<strong>{formatMoney(state.cashMovements.filter((movement) => movement.type === 'Ingreso' && movement.method === item).reduce((sum, movement) => sum + movement.amount, 0))}</strong></span>)}</div><div className="formula-block">Fondo inicial + ingresos − egresos = efectivo esperado<br /><strong>{formatMoney(session.openingAmount)} + {formatMoney(income)} − {formatMoney(expenses)} = {formatMoney(expected)}</strong></div></section></div><div className="filter-bar"><label>Tipo<select value={type} onChange={(event) => setType(event.target.value)}><option>Todos</option><option>Ingreso</option><option>Egreso</option></select></label><label>Método<select value={method} onChange={(event) => setMethod(event.target.value)}><option>Todos</option>{methods.map((item) => <option key={item}>{item}</option>)}</select></label></div><DataTable caption="Movimientos de la sesión de caja actual" columns={['Movimiento', 'Tipo', 'Concepto', 'Referencia', 'Método', 'Importe', 'Fecha y hora']}>{records.length ? records.map((item) => <tr key={item.id}><td>{item.id}</td><td><StatusBadge>{item.type}</StatusBadge></td><td>{item.concept}</td><td>{item.referenceId || 'Sin referencia'}</td><td>{item.method}</td><td>{formatMoney(item.amount)}</td><td>{formatDateTime(item.createdAt)}</td></tr>) : null}</DataTable><button className="btn btn-outline" disabled>Cerrar caja: requiere conteo y autorización no implementados</button></div>;
}

export function ReportsView() {
  const { state } = useHotel();
  const [report, setReport] = useState('habitaciones');
  const roomCharges = state.accounts.flatMap((item) => item.charges);
  const reports = {
    habitaciones: ROOM_STATUSES.map((item) => ({ label: item, value: state.rooms.filter((room) => room.status === item).length })),
    finanzas: [...new Set(state.payments.map((item) => item.method))].map((item) => ({ label: item, value: formatMoney(state.payments.filter((payment) => payment.method === item).reduce((sum, payment) => sum + payment.amount, 0)) })),
    clientes: state.clients.map((item) => ({ label: item.name, value: `${state.reservations.filter((reservation) => reservation.clientId === item.id).length} reservas · ${state.stays.filter((stay) => stay.clientId === item.id).length} estadías · ${formatMoney(state.payments.filter((payment) => payment.clientId === item.id).reduce((sum, payment) => sum + payment.amount, 0))} en pagos visibles` })),
    pedidos: ORDER_STATUSES.map((item) => ({ label: item, value: state.orders.filter((order) => order.status === item).length })),
    inventario: state.inventory.map((item) => ({ label: item.name, value: `${inventoryAvailable(item)} ${item.unit} disponibles${inventoryAvailable(item) < 0 ? ' · sobre-reservado' : ''}` })),
    personal: state.staff.map((item) => ({ label: `${item.name} · ${item.area}`, value: `${item.overtimeHours} h extra · ${item.attendance}` })),
    eventos: state.events.map((item) => ({ label: `${item.date} · ${item.title}`, value: `${item.venue} · ${formatMoney(item.total)}` })),
    encuestas: state.surveys.map((item) => ({ label: selectClientName(state, item.clientId), value: item.overall ? `${item.overall}/5 · ${item.status}` : item.status })),
    recreacion: state.recreationAccess.map((item) => ({ label: `${item.zone} · Hab. ${item.roomId}`, value: `${item.peopleInside}/${item.allowedPeople} dentro · ${item.status}` })),
  };
  return <div className="view-container"><PageHeader metadata="Corte de registros actuales" title="Reportes de sesión" description="Lecturas operativas por módulo sin atribuir períodos históricos que el frontend no conserva." /><MetricStrip items={[{ label: 'Habitaciones ocupadas', value: state.rooms.filter((item) => item.status === 'Ocupada').length }, { label: 'Pagos registrados', value: formatMoney(state.payments.reduce((sum, item) => sum + item.amount, 0)) }, { label: 'Cargos visibles', value: formatMoney(roomCharges.reduce((sum, item) => sum + item.amount, 0)) }, { label: 'Pedidos', value: state.orders.length }, { label: 'Eventos', value: state.events.length }]} /><div className="report-selector" role="group" aria-label="Seleccionar reporte">{Object.keys(reports).map((key) => <button key={key} className={report === key ? 'active' : ''} onClick={() => setReport(key)}>{({ habitaciones: 'Habitaciones', finanzas: 'Finanzas', clientes: 'Clientes', pedidos: 'Pedidos', inventario: 'Inventario', personal: 'Personal', eventos: 'Eventos', encuestas: 'Encuestas', recreacion: 'Recreación' })[key]}</button>)}</div><section className="card"><SectionHeader eyebrow="Registros visibles" title={`Reporte de ${{ habitaciones: 'habitaciones', finanzas: 'finanzas', clientes: 'clientes', pedidos: 'pedidos', inventario: 'inventario', personal: 'personal', eventos: 'eventos', encuestas: 'encuestas', recreacion: 'recreación' }[report]}`} /><div className="report-grid">{reports[report].map((item) => <div key={`${item.label}-${item.value}`}><span>{item.label}</span><strong>{item.value}</strong></div>)}</div></section><PrototypeNotice>no hay persistencia ni selección histórica. Estos reportes describen exclusivamente el estado cargado y mutado durante la sesión actual.</PrototypeNotice></div>;
}
