import { useEffect, useState } from 'react';
import { formatMoney } from '../../../domain/hotelModel';
import { useCollectionTable } from '../../../hooks/useCollectionTable';
import { useHotel } from '../../../state/hotelContext';
import { Pagination, RowActions, SortableHeader } from '../../ui/CollectionTable';
import { executeWithFeedback } from '../../ui/actionFeedback';
import { Dialog, Drawer } from '../../ui/Overlay';
import { DetailGrid, EmptyState, MetricStrip, PageHeader, StatusBadge } from '../SharedViewParts';

function RoomForm({ room, onClose, notify }) {
  const { execute } = useHotel();
  const [form, setForm] = useState({ nightlyRate: room.nightlyRate, capacity: room.capacity, beds: room.beds, amenities: { ...room.amenities } });
  const submit = (event) => { event.preventDefault(); if (executeWithFeedback(execute, { type: 'ROOM_UPDATE', roomId: room.id, payload: form }, notify, { title: 'Habitación actualizada', message: 'Sólo se editaron atributos maestros; el estado derivado no fue alterado.' })) onClose(); };
  return <form className="form-grid" onSubmit={submit}><label>Tarifa por noche<input type="number" min="0" value={form.nightlyRate} onChange={(event) => setForm({ ...form, nightlyRate: event.target.value })} /></label><label>Capacidad<input type="number" min="1" value={form.capacity} onChange={(event) => setForm({ ...form, capacity: event.target.value })} /></label><label className="span-2">Camas<input required value={form.beds} onChange={(event) => setForm({ ...form, beds: event.target.value })} /></label><fieldset className="option-fieldset span-2"><legend>Comodidades</legend>{Object.entries(form.amenities).map(([key, enabled]) => <label className="check-option" key={key}><input type="checkbox" checked={enabled} onChange={(event) => setForm({ ...form, amenities: { ...form.amenities, [key]: event.target.checked } })} />{({ airConditioning: 'Aire acondicionado', television: 'Televisor', hotWater: 'Agua caliente', wifi: 'Wi-Fi', minibar: 'Frigobar' })[key]}</label>)}</fieldset><div className="form-actions span-2"><button type="button" className="btn btn-outline" onClick={onClose}>Cancelar</button><button className="btn btn-primary">Guardar atributos</button></div></form>;
}

export default function RoomsView({ notify, navigationIntent, consumeNavigationIntent }) {
  const { state, execute } = useHotel();
  const [status, setStatus] = useState('Todos');
  const [selectedId, setSelectedId] = useState(null);
  const [editorId, setEditorId] = useState(null);
  useEffect(() => { if (navigationIntent?.type === 'select-record') { setSelectedId(navigationIntent.recordId); consumeNavigationIntent(navigationIntent.id); } }, [navigationIntent, consumeNavigationIntent]);
  const records = state.rooms.filter((item) => status === 'Todos' || item.status === status);
  const table = useCollectionTable(records, 'id', 10, JSON.stringify([status, records.map((item) => item.id)]));
  const selected = state.rooms.find((item) => item.id === selectedId);
  const editor = state.rooms.find((item) => item.id === editorId);
  const block = (room) => executeWithFeedback(execute, { type: room.operationalBlock ? 'ROOM_UNBLOCK' : 'ROOM_BLOCK', roomId: room.id, reason: 'Acción contextual desde listado de habitaciones', responsible: 'Administrador demo' }, notify, { title: room.operationalBlock ? 'Habitación desbloqueada' : 'Habitación bloqueada', message: 'La transición quedó auditada con actor y fecha.' });
  const columns = [{ key: 'id', label: 'Habitación' }, { key: 'floor', label: 'Piso' }, { key: 'category', label: 'Categoría' }, { key: 'capacity', label: 'Capacidad' }, { key: 'nightlyRate', label: 'Tarifa' }, { key: 'status', label: 'Estado' }];
  return <div className="view-container"><PageHeader metadata="38 habitaciones · estados derivados protegidos" title="Maestro de habitaciones" description="Tarifa, capacidad, comodidades y bloqueo administrativo auditable." /><MetricStrip items={[{ label: 'Disponibles', value: state.rooms.filter((item) => item.status === 'Disponible').length }, { label: 'Bloqueadas', value: state.rooms.filter((item) => item.operationalBlock).length }, { label: 'Ocupadas', value: state.rooms.filter((item) => item.activeStayId).length }]} /><div className="filter-bar"><label>Estado<select value={status} onChange={(event) => setStatus(event.target.value)}><option>Todos</option>{[...new Set(state.rooms.map((item) => item.status))].map((item) => <option key={item}>{item}</option>)}</select></label><span className="filter-result">{records.length} habitaciones</span></div>{table.total ? <section className="card table-container"><table className="custom-table"><caption>Habitaciones y estado operativo</caption><thead><tr>{columns.map((column) => <SortableHeader key={column.key} column={column} sort={table.sort} onSort={table.toggleSort} />)}<th scope="col">Acciones</th></tr></thead><tbody>{table.visible.map((room) => <tr key={room.id}><td><strong>{room.id}</strong></td><td>{room.floor}</td><td>{room.category}</td><td>{room.capacity} persona(s)<br /><small>{room.beds}</small></td><td>{formatMoney(room.nightlyRate)}</td><td><StatusBadge>{room.status}</StatusBadge></td><td><RowActions label={`habitación ${room.id}`}><button role="menuitem" onClick={() => setSelectedId(room.id)}>Ver detalle</button><button role="menuitem" onClick={() => setEditorId(room.id)}>Editar maestro</button><button role="menuitem" onClick={() => block(room)}>{room.operationalBlock ? 'Desbloquear' : 'Bloquear'}</button></RowActions></td></tr>)}</tbody></table><Pagination {...table} onPage={table.setPage} /></section> : <EmptyState title="Sin habitaciones" />}<Drawer open={Boolean(selected)} onClose={() => setSelectedId(null)} title={selected ? `Habitación ${selected.id}` : 'Habitación'}>{selected ? <DetailGrid items={[{ label: 'Estado', node: <StatusBadge>{selected.status}</StatusBadge> }, { label: 'Categoría', value: selected.category }, { label: 'Tarifa', value: formatMoney(selected.nightlyRate) }, { label: 'Capacidad', value: selected.capacity }, { label: 'Limpieza', value: selected.cleaningStatus }, { label: 'Bloqueo', value: selected.blockReason || 'Sin bloqueo administrativo' }]} /> : null}</Drawer><Dialog open={Boolean(editor)} onClose={() => setEditorId(null)} title={editor ? `Editar habitación ${editor.id}` : 'Editar habitación'}>{editor ? <RoomForm room={editor} onClose={() => setEditorId(null)} notify={notify} /> : null}</Dialog></div>;
}
